changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - bot
  categories:
    - title: "✨ New Features"
      labels:
        - feat
        - feature
        - enhancement
    - title: "🐛 Bug Fixes"
      labels:
        - fix
        - bug
    - title: "🛠 Refactor"
      labels:
        - refactor
    - title: "🚀 Performance"
      labels:
        - perf
    - title: "📝 Documentation"
      labels:
        - docs
        - documentation
    - title: "🧪 Tests"
      labels:
        - test
        - tests
    - title: "🧹 Chore"
      labels:
        - chore
        - dependencies
    - title: "📦 Build & CI"
      labels:
        - build
        - ci
