// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PbPageResIdl.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from PbPageResIdl.proto</summary>
public static partial class PbPageResIdlReflection {

  #region Descriptor
  /// <summary>File descriptor for PbPageResIdl.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static PbPageResIdlReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChJQYlBhZ2VSZXNJZGwucHJvdG8aC0Vycm9yLnByb3RvGhFTaW1wbGVGb3J1",
          "bS5wcm90bxoKUGFnZS5wcm90bxoKUG9zdC5wcm90bxoQVGhyZWFkSW5mby5w",
          "cm90bxoKVXNlci5wcm90byLyAQoMUGJQYWdlUmVzSWRsEhUKBWVycm9yGAEg",
          "ASgLMgYuRXJyb3ISIwoEZGF0YRgCIAEoCzIVLlBiUGFnZVJlc0lkbC5EYXRh",
          "UmVzGqUBCgdEYXRhUmVzEhsKBWZvcnVtGAIgASgLMgwuU2ltcGxlRm9ydW0S",
          "EwoEcGFnZRgDIAEoCzIFLlBhZ2USGAoJcG9zdF9saXN0GAYgAygLMgUuUG9z",
          "dBIbCgZ0aHJlYWQYCCABKAsyCy5UaHJlYWRJbmZvEhgKCXVzZXJfbGlzdBgN",
          "IAMoCzIFLlVzZXISFwoPdGhyZWFkX2ZyZXFfbnVtGCUgASgDYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::ErrorReflection.Descriptor, global::SimpleForumReflection.Descriptor, global::PageReflection.Descriptor, global::PostReflection.Descriptor, global::ThreadInfoReflection.Descriptor, global::UserReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::PbPageResIdl), global::PbPageResIdl.Parser, new[]{ "Error", "Data" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::PbPageResIdl.Types.DataRes), global::PbPageResIdl.Types.DataRes.Parser, new[]{ "Forum", "Page", "PostList", "Thread", "UserList", "ThreadFreqNum" }, null, null, null, null)})
        }));
  }
  #endregion

}
#region Messages
[global::System.SerializableAttribute]
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class PbPageResIdl : pb::IMessage<PbPageResIdl>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<PbPageResIdl> _parser = new pb::MessageParser<PbPageResIdl>(() => new PbPageResIdl());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<PbPageResIdl> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PbPageResIdlReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PbPageResIdl() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PbPageResIdl(PbPageResIdl other) : this() {
    error_ = other.error_ != null ? other.error_.Clone() : null;
    data_ = other.data_ != null ? other.data_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PbPageResIdl Clone() {
    return new PbPageResIdl(this);
  }

  /// <summary>Field number for the "error" field.</summary>
  public const int ErrorFieldNumber = 1;
  private global::Error error_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Error Error {
    get { return error_; }
    set {
      error_ = value;
    }
  }

  /// <summary>Field number for the "data" field.</summary>
  public const int DataFieldNumber = 2;
  private global::PbPageResIdl.Types.DataRes data_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::PbPageResIdl.Types.DataRes Data {
    get { return data_; }
    set {
      data_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as PbPageResIdl);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(PbPageResIdl other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Error, other.Error)) return false;
    if (!object.Equals(Data, other.Data)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (error_ != null) hash ^= Error.GetHashCode();
    if (data_ != null) hash ^= Data.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (error_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Error);
    }
    if (data_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Data);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (error_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Error);
    }
    if (data_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Data);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (error_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Error);
    }
    if (data_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(PbPageResIdl other) {
    if (other == null) {
      return;
    }
    if (other.error_ != null) {
      if (error_ == null) {
        Error = new global::Error();
      }
      Error.MergeFrom(other.Error);
    }
    if (other.data_ != null) {
      if (data_ == null) {
        Data = new global::PbPageResIdl.Types.DataRes();
      }
      Data.MergeFrom(other.Data);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (error_ == null) {
            Error = new global::Error();
          }
          input.ReadMessage(Error);
          break;
        }
        case 18: {
          if (data_ == null) {
            Data = new global::PbPageResIdl.Types.DataRes();
          }
          input.ReadMessage(Data);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (error_ == null) {
            Error = new global::Error();
          }
          input.ReadMessage(Error);
          break;
        }
        case 18: {
          if (data_ == null) {
            Data = new global::PbPageResIdl.Types.DataRes();
          }
          input.ReadMessage(Data);
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the PbPageResIdl message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    [global::System.SerializableAttribute]
    [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
    public sealed partial class DataRes : pb::IMessage<DataRes>
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
    #endif
    {
      private static readonly pb::MessageParser<DataRes> _parser = new pb::MessageParser<DataRes>(() => new DataRes());
      private pb::UnknownFieldSet _unknownFields;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pb::MessageParser<DataRes> Parser { get { return _parser; } }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pbr::MessageDescriptor Descriptor {
        get { return global::PbPageResIdl.Descriptor.NestedTypes[0]; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      pbr::MessageDescriptor pb::IMessage.Descriptor {
        get { return Descriptor; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public DataRes() {
        OnConstruction();
      }

      partial void OnConstruction();

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public DataRes(DataRes other) : this() {
        forum_ = other.forum_ != null ? other.forum_.Clone() : null;
        page_ = other.page_ != null ? other.page_.Clone() : null;
        postList_ = other.postList_.Clone();
        thread_ = other.thread_ != null ? other.thread_.Clone() : null;
        userList_ = other.userList_.Clone();
        threadFreqNum_ = other.threadFreqNum_;
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public DataRes Clone() {
        return new DataRes(this);
      }

      /// <summary>Field number for the "forum" field.</summary>
      public const int ForumFieldNumber = 2;
      private global::SimpleForum forum_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public global::SimpleForum Forum {
        get { return forum_; }
        set {
          forum_ = value;
        }
      }

      /// <summary>Field number for the "page" field.</summary>
      public const int PageFieldNumber = 3;
      private global::Page page_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public global::Page Page {
        get { return page_; }
        set {
          page_ = value;
        }
      }

      /// <summary>Field number for the "post_list" field.</summary>
      public const int PostListFieldNumber = 6;
      private static readonly pb::FieldCodec<global::Post> _repeated_postList_codec
          = pb::FieldCodec.ForMessage(50, global::Post.Parser);
      private readonly pbc::RepeatedField<global::Post> postList_ = new pbc::RepeatedField<global::Post>();
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public pbc::RepeatedField<global::Post> PostList {
        get { return postList_; }
      }

      /// <summary>Field number for the "thread" field.</summary>
      public const int ThreadFieldNumber = 8;
      private global::ThreadInfo thread_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public global::ThreadInfo Thread {
        get { return thread_; }
        set {
          thread_ = value;
        }
      }

      /// <summary>Field number for the "user_list" field.</summary>
      public const int UserListFieldNumber = 13;
      private static readonly pb::FieldCodec<global::User> _repeated_userList_codec
          = pb::FieldCodec.ForMessage(106, global::User.Parser);
      private readonly pbc::RepeatedField<global::User> userList_ = new pbc::RepeatedField<global::User>();
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public pbc::RepeatedField<global::User> UserList {
        get { return userList_; }
      }

      /// <summary>Field number for the "thread_freq_num" field.</summary>
      public const int ThreadFreqNumFieldNumber = 37;
      private long threadFreqNum_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public long ThreadFreqNum {
        get { return threadFreqNum_; }
        set {
          threadFreqNum_ = value;
        }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override bool Equals(object other) {
        return Equals(other as DataRes);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool Equals(DataRes other) {
        if (ReferenceEquals(other, null)) {
          return false;
        }
        if (ReferenceEquals(other, this)) {
          return true;
        }
        if (!object.Equals(Forum, other.Forum)) return false;
        if (!object.Equals(Page, other.Page)) return false;
        if(!postList_.Equals(other.postList_)) return false;
        if (!object.Equals(Thread, other.Thread)) return false;
        if(!userList_.Equals(other.userList_)) return false;
        if (ThreadFreqNum != other.ThreadFreqNum) return false;
        return Equals(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override int GetHashCode() {
        int hash = 1;
        if (forum_ != null) hash ^= Forum.GetHashCode();
        if (page_ != null) hash ^= Page.GetHashCode();
        hash ^= postList_.GetHashCode();
        if (thread_ != null) hash ^= Thread.GetHashCode();
        hash ^= userList_.GetHashCode();
        if (ThreadFreqNum != 0L) hash ^= ThreadFreqNum.GetHashCode();
        if (_unknownFields != null) {
          hash ^= _unknownFields.GetHashCode();
        }
        return hash;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override string ToString() {
        return pb::JsonFormatter.ToDiagnosticString(this);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void WriteTo(pb::CodedOutputStream output) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        output.WriteRawMessage(this);
      #else
        if (forum_ != null) {
          output.WriteRawTag(18);
          output.WriteMessage(Forum);
        }
        if (page_ != null) {
          output.WriteRawTag(26);
          output.WriteMessage(Page);
        }
        postList_.WriteTo(output, _repeated_postList_codec);
        if (thread_ != null) {
          output.WriteRawTag(66);
          output.WriteMessage(Thread);
        }
        userList_.WriteTo(output, _repeated_userList_codec);
        if (ThreadFreqNum != 0L) {
          output.WriteRawTag(168, 2);
          output.WriteInt64(ThreadFreqNum);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(output);
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
        if (forum_ != null) {
          output.WriteRawTag(18);
          output.WriteMessage(Forum);
        }
        if (page_ != null) {
          output.WriteRawTag(26);
          output.WriteMessage(Page);
        }
        postList_.WriteTo(ref output, _repeated_postList_codec);
        if (thread_ != null) {
          output.WriteRawTag(66);
          output.WriteMessage(Thread);
        }
        userList_.WriteTo(ref output, _repeated_userList_codec);
        if (ThreadFreqNum != 0L) {
          output.WriteRawTag(168, 2);
          output.WriteInt64(ThreadFreqNum);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(ref output);
        }
      }
      #endif

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public int CalculateSize() {
        int size = 0;
        if (forum_ != null) {
          size += 1 + pb::CodedOutputStream.ComputeMessageSize(Forum);
        }
        if (page_ != null) {
          size += 1 + pb::CodedOutputStream.ComputeMessageSize(Page);
        }
        size += postList_.CalculateSize(_repeated_postList_codec);
        if (thread_ != null) {
          size += 1 + pb::CodedOutputStream.ComputeMessageSize(Thread);
        }
        size += userList_.CalculateSize(_repeated_userList_codec);
        if (ThreadFreqNum != 0L) {
          size += 2 + pb::CodedOutputStream.ComputeInt64Size(ThreadFreqNum);
        }
        if (_unknownFields != null) {
          size += _unknownFields.CalculateSize();
        }
        return size;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(DataRes other) {
        if (other == null) {
          return;
        }
        if (other.forum_ != null) {
          if (forum_ == null) {
            Forum = new global::SimpleForum();
          }
          Forum.MergeFrom(other.Forum);
        }
        if (other.page_ != null) {
          if (page_ == null) {
            Page = new global::Page();
          }
          Page.MergeFrom(other.Page);
        }
        postList_.Add(other.postList_);
        if (other.thread_ != null) {
          if (thread_ == null) {
            Thread = new global::ThreadInfo();
          }
          Thread.MergeFrom(other.Thread);
        }
        userList_.Add(other.userList_);
        if (other.ThreadFreqNum != 0L) {
          ThreadFreqNum = other.ThreadFreqNum;
        }
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(pb::CodedInputStream input) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        input.ReadRawMessage(this);
      #else
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
        if ((tag & 7) == 4) {
          // Abort on any end group tag.
          return;
        }
        switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
              break;
            case 18: {
              if (forum_ == null) {
                Forum = new global::SimpleForum();
              }
              input.ReadMessage(Forum);
              break;
            }
            case 26: {
              if (page_ == null) {
                Page = new global::Page();
              }
              input.ReadMessage(Page);
              break;
            }
            case 50: {
              postList_.AddEntriesFrom(input, _repeated_postList_codec);
              break;
            }
            case 66: {
              if (thread_ == null) {
                Thread = new global::ThreadInfo();
              }
              input.ReadMessage(Thread);
              break;
            }
            case 106: {
              userList_.AddEntriesFrom(input, _repeated_userList_codec);
              break;
            }
            case 296: {
              ThreadFreqNum = input.ReadInt64();
              break;
            }
          }
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
        if ((tag & 7) == 4) {
          // Abort on any end group tag.
          return;
        }
        switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
              break;
            case 18: {
              if (forum_ == null) {
                Forum = new global::SimpleForum();
              }
              input.ReadMessage(Forum);
              break;
            }
            case 26: {
              if (page_ == null) {
                Page = new global::Page();
              }
              input.ReadMessage(Page);
              break;
            }
            case 50: {
              postList_.AddEntriesFrom(ref input, _repeated_postList_codec);
              break;
            }
            case 66: {
              if (thread_ == null) {
                Thread = new global::ThreadInfo();
              }
              input.ReadMessage(Thread);
              break;
            }
            case 106: {
              userList_.AddEntriesFrom(ref input, _repeated_userList_codec);
              break;
            }
            case 296: {
              ThreadFreqNum = input.ReadInt64();
              break;
            }
          }
        }
      }
      #endif

    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
