// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GetGroupMsgResIdl.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from GetGroupMsgResIdl.proto</summary>
internal static partial class GetGroupMsgResIdlReflection {

  #region Descriptor
  /// <summary>File descriptor for GetGroupMsgResIdl.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GetGroupMsgResIdlReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChdHZXRHcm91cE1zZ1Jlc0lkbC5wcm90bxoLRXJyb3IucHJvdG8irwQKEUdl",
          "dEdyb3VwTXNnUmVzSWRsEhUKBWVycm9yGAEgASgLMgYuRXJyb3ISKAoEZGF0",
          "YRgCIAEoCzIaLkdldEdyb3VwTXNnUmVzSWRsLkRhdGFSZXMa2AMKB0RhdGFS",
          "ZXMSNgoJZ3JvdXBJbmZvGAEgAygLMiMuR2V0R3JvdXBNc2dSZXNJZGwuRGF0",
          "YVJlcy5Hcm91cE1zZxqUAwoIR3JvdXBNc2cSQAoJZ3JvdXBJbmZvGAEgASgL",
          "Mi0uR2V0R3JvdXBNc2dSZXNJZGwuRGF0YVJlcy5Hcm91cE1zZy5Hcm91cElu",
          "Zm8SPAoHbXNnTGlzdBgCIAMoCzIrLkdldEdyb3VwTXNnUmVzSWRsLkRhdGFS",
          "ZXMuR3JvdXBNc2cuTXNnSW5mbxovCglHcm91cEluZm8SDwoHZ3JvdXBJZBgB",
          "IAEoAxIRCglncm91cFR5cGUYFCABKAUa1gEKB01zZ0luZm8SDQoFbXNnSWQY",
          "ASABKAMSDwoHbXNnVHlwZRgDIAEoBRIPCgdjb250ZW50GAUgASgJEhIKCmNy",
          "ZWF0ZVRpbWUYCCABKAUSRgoIdXNlckluZm8YCiABKAsyNC5HZXRHcm91cE1z",
          "Z1Jlc0lkbC5EYXRhUmVzLkdyb3VwTXNnLk1zZ0luZm8uVXNlckluZm8aPgoI",
          "VXNlckluZm8SDgoGdXNlcklkGAEgASgDEhAKCHVzZXJOYW1lGAIgASgJEhAK",
          "CHBvcnRyYWl0GAQgASgJYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::ErrorReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::GetGroupMsgResIdl), global::GetGroupMsgResIdl.Parser, new[]{ "Error", "Data" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::GetGroupMsgResIdl.Types.DataRes), global::GetGroupMsgResIdl.Types.DataRes.Parser, new[]{ "GroupInfo" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::GetGroupMsgResIdl.Types.DataRes.Types.GroupMsg), global::GetGroupMsgResIdl.Types.DataRes.Types.GroupMsg.Parser, new[]{ "GroupInfo", "MsgList" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::GetGroupMsgResIdl.Types.DataRes.Types.GroupMsg.Types.GroupInfo), global::GetGroupMsgResIdl.Types.DataRes.Types.GroupMsg.Types.GroupInfo.Parser, new[]{ "GroupId", "GroupType" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::GetGroupMsgResIdl.Types.DataRes.Types.GroupMsg.Types.MsgInfo), global::GetGroupMsgResIdl.Types.DataRes.Types.GroupMsg.Types.MsgInfo.Parser, new[]{ "MsgId", "MsgType", "Content", "CreateTime", "UserInfo" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::GetGroupMsgResIdl.Types.DataRes.Types.GroupMsg.Types.MsgInfo.Types.UserInfo), global::GetGroupMsgResIdl.Types.DataRes.Types.GroupMsg.Types.MsgInfo.Types.UserInfo.Parser, new[]{ "UserId", "UserName", "Portrait" }, null, null, null, null)})})})})
        }));
  }
  #endregion

}
#region Messages
[global::System.SerializableAttribute]
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
internal sealed partial class GetGroupMsgResIdl : pb::IMessage<GetGroupMsgResIdl>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GetGroupMsgResIdl> _parser = new pb::MessageParser<GetGroupMsgResIdl>(() => new GetGroupMsgResIdl());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GetGroupMsgResIdl> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetGroupMsgResIdlReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetGroupMsgResIdl() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetGroupMsgResIdl(GetGroupMsgResIdl other) : this() {
    error_ = other.error_ != null ? other.error_.Clone() : null;
    data_ = other.data_ != null ? other.data_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetGroupMsgResIdl Clone() {
    return new GetGroupMsgResIdl(this);
  }

  /// <summary>Field number for the "error" field.</summary>
  public const int ErrorFieldNumber = 1;
  private global::Error error_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Error Error {
    get { return error_; }
    set {
      error_ = value;
    }
  }

  /// <summary>Field number for the "data" field.</summary>
  public const int DataFieldNumber = 2;
  private global::GetGroupMsgResIdl.Types.DataRes data_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::GetGroupMsgResIdl.Types.DataRes Data {
    get { return data_; }
    set {
      data_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GetGroupMsgResIdl);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GetGroupMsgResIdl other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Error, other.Error)) return false;
    if (!object.Equals(Data, other.Data)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (error_ != null) hash ^= Error.GetHashCode();
    if (data_ != null) hash ^= Data.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (error_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Error);
    }
    if (data_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Data);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (error_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Error);
    }
    if (data_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Data);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (error_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Error);
    }
    if (data_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GetGroupMsgResIdl other) {
    if (other == null) {
      return;
    }
    if (other.error_ != null) {
      if (error_ == null) {
        Error = new global::Error();
      }
      Error.MergeFrom(other.Error);
    }
    if (other.data_ != null) {
      if (data_ == null) {
        Data = new global::GetGroupMsgResIdl.Types.DataRes();
      }
      Data.MergeFrom(other.Data);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (error_ == null) {
            Error = new global::Error();
          }
          input.ReadMessage(Error);
          break;
        }
        case 18: {
          if (data_ == null) {
            Data = new global::GetGroupMsgResIdl.Types.DataRes();
          }
          input.ReadMessage(Data);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (error_ == null) {
            Error = new global::Error();
          }
          input.ReadMessage(Error);
          break;
        }
        case 18: {
          if (data_ == null) {
            Data = new global::GetGroupMsgResIdl.Types.DataRes();
          }
          input.ReadMessage(Data);
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the GetGroupMsgResIdl message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    [global::System.SerializableAttribute]
    [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
    internal sealed partial class DataRes : pb::IMessage<DataRes>
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
    #endif
    {
      private static readonly pb::MessageParser<DataRes> _parser = new pb::MessageParser<DataRes>(() => new DataRes());
      private pb::UnknownFieldSet _unknownFields;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pb::MessageParser<DataRes> Parser { get { return _parser; } }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pbr::MessageDescriptor Descriptor {
        get { return global::GetGroupMsgResIdl.Descriptor.NestedTypes[0]; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      pbr::MessageDescriptor pb::IMessage.Descriptor {
        get { return Descriptor; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public DataRes() {
        OnConstruction();
      }

      partial void OnConstruction();

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public DataRes(DataRes other) : this() {
        groupInfo_ = other.groupInfo_.Clone();
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public DataRes Clone() {
        return new DataRes(this);
      }

      /// <summary>Field number for the "groupInfo" field.</summary>
      public const int GroupInfoFieldNumber = 1;
      private static readonly pb::FieldCodec<global::GetGroupMsgResIdl.Types.DataRes.Types.GroupMsg> _repeated_groupInfo_codec
          = pb::FieldCodec.ForMessage(10, global::GetGroupMsgResIdl.Types.DataRes.Types.GroupMsg.Parser);
      private readonly pbc::RepeatedField<global::GetGroupMsgResIdl.Types.DataRes.Types.GroupMsg> groupInfo_ = new pbc::RepeatedField<global::GetGroupMsgResIdl.Types.DataRes.Types.GroupMsg>();
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public pbc::RepeatedField<global::GetGroupMsgResIdl.Types.DataRes.Types.GroupMsg> GroupInfo {
        get { return groupInfo_; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override bool Equals(object other) {
        return Equals(other as DataRes);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool Equals(DataRes other) {
        if (ReferenceEquals(other, null)) {
          return false;
        }
        if (ReferenceEquals(other, this)) {
          return true;
        }
        if(!groupInfo_.Equals(other.groupInfo_)) return false;
        return Equals(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override int GetHashCode() {
        int hash = 1;
        hash ^= groupInfo_.GetHashCode();
        if (_unknownFields != null) {
          hash ^= _unknownFields.GetHashCode();
        }
        return hash;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override string ToString() {
        return pb::JsonFormatter.ToDiagnosticString(this);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void WriteTo(pb::CodedOutputStream output) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        output.WriteRawMessage(this);
      #else
        groupInfo_.WriteTo(output, _repeated_groupInfo_codec);
        if (_unknownFields != null) {
          _unknownFields.WriteTo(output);
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
        groupInfo_.WriteTo(ref output, _repeated_groupInfo_codec);
        if (_unknownFields != null) {
          _unknownFields.WriteTo(ref output);
        }
      }
      #endif

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public int CalculateSize() {
        int size = 0;
        size += groupInfo_.CalculateSize(_repeated_groupInfo_codec);
        if (_unknownFields != null) {
          size += _unknownFields.CalculateSize();
        }
        return size;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(DataRes other) {
        if (other == null) {
          return;
        }
        groupInfo_.Add(other.groupInfo_);
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(pb::CodedInputStream input) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        input.ReadRawMessage(this);
      #else
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
        if ((tag & 7) == 4) {
          // Abort on any end group tag.
          return;
        }
        switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
              break;
            case 10: {
              groupInfo_.AddEntriesFrom(input, _repeated_groupInfo_codec);
              break;
            }
          }
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
        if ((tag & 7) == 4) {
          // Abort on any end group tag.
          return;
        }
        switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
              break;
            case 10: {
              groupInfo_.AddEntriesFrom(ref input, _repeated_groupInfo_codec);
              break;
            }
          }
        }
      }
      #endif

      #region Nested types
      /// <summary>Container for nested types declared in the DataRes message type.</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static partial class Types {
        [global::System.SerializableAttribute]
        [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
        internal sealed partial class GroupMsg : pb::IMessage<GroupMsg>
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            , pb::IBufferMessage
        #endif
        {
          private static readonly pb::MessageParser<GroupMsg> _parser = new pb::MessageParser<GroupMsg>(() => new GroupMsg());
          private pb::UnknownFieldSet _unknownFields;
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public static pb::MessageParser<GroupMsg> Parser { get { return _parser; } }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public static pbr::MessageDescriptor Descriptor {
            get { return global::GetGroupMsgResIdl.Types.DataRes.Descriptor.NestedTypes[0]; }
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          pbr::MessageDescriptor pb::IMessage.Descriptor {
            get { return Descriptor; }
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public GroupMsg() {
            OnConstruction();
          }

          partial void OnConstruction();

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public GroupMsg(GroupMsg other) : this() {
            groupInfo_ = other.groupInfo_ != null ? other.groupInfo_.Clone() : null;
            msgList_ = other.msgList_.Clone();
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public GroupMsg Clone() {
            return new GroupMsg(this);
          }

          /// <summary>Field number for the "groupInfo" field.</summary>
          public const int GroupInfoFieldNumber = 1;
          private global::GetGroupMsgResIdl.Types.DataRes.Types.GroupMsg.Types.GroupInfo groupInfo_;
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public global::GetGroupMsgResIdl.Types.DataRes.Types.GroupMsg.Types.GroupInfo GroupInfo {
            get { return groupInfo_; }
            set {
              groupInfo_ = value;
            }
          }

          /// <summary>Field number for the "msgList" field.</summary>
          public const int MsgListFieldNumber = 2;
          private static readonly pb::FieldCodec<global::GetGroupMsgResIdl.Types.DataRes.Types.GroupMsg.Types.MsgInfo> _repeated_msgList_codec
              = pb::FieldCodec.ForMessage(18, global::GetGroupMsgResIdl.Types.DataRes.Types.GroupMsg.Types.MsgInfo.Parser);
          private readonly pbc::RepeatedField<global::GetGroupMsgResIdl.Types.DataRes.Types.GroupMsg.Types.MsgInfo> msgList_ = new pbc::RepeatedField<global::GetGroupMsgResIdl.Types.DataRes.Types.GroupMsg.Types.MsgInfo>();
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public pbc::RepeatedField<global::GetGroupMsgResIdl.Types.DataRes.Types.GroupMsg.Types.MsgInfo> MsgList {
            get { return msgList_; }
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public override bool Equals(object other) {
            return Equals(other as GroupMsg);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public bool Equals(GroupMsg other) {
            if (ReferenceEquals(other, null)) {
              return false;
            }
            if (ReferenceEquals(other, this)) {
              return true;
            }
            if (!object.Equals(GroupInfo, other.GroupInfo)) return false;
            if(!msgList_.Equals(other.msgList_)) return false;
            return Equals(_unknownFields, other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public override int GetHashCode() {
            int hash = 1;
            if (groupInfo_ != null) hash ^= GroupInfo.GetHashCode();
            hash ^= msgList_.GetHashCode();
            if (_unknownFields != null) {
              hash ^= _unknownFields.GetHashCode();
            }
            return hash;
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public override string ToString() {
            return pb::JsonFormatter.ToDiagnosticString(this);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public void WriteTo(pb::CodedOutputStream output) {
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
          #else
            if (groupInfo_ != null) {
              output.WriteRawTag(10);
              output.WriteMessage(GroupInfo);
            }
            msgList_.WriteTo(output, _repeated_msgList_codec);
            if (_unknownFields != null) {
              _unknownFields.WriteTo(output);
            }
          #endif
          }

          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
            if (groupInfo_ != null) {
              output.WriteRawTag(10);
              output.WriteMessage(GroupInfo);
            }
            msgList_.WriteTo(ref output, _repeated_msgList_codec);
            if (_unknownFields != null) {
              _unknownFields.WriteTo(ref output);
            }
          }
          #endif

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public int CalculateSize() {
            int size = 0;
            if (groupInfo_ != null) {
              size += 1 + pb::CodedOutputStream.ComputeMessageSize(GroupInfo);
            }
            size += msgList_.CalculateSize(_repeated_msgList_codec);
            if (_unknownFields != null) {
              size += _unknownFields.CalculateSize();
            }
            return size;
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public void MergeFrom(GroupMsg other) {
            if (other == null) {
              return;
            }
            if (other.groupInfo_ != null) {
              if (groupInfo_ == null) {
                GroupInfo = new global::GetGroupMsgResIdl.Types.DataRes.Types.GroupMsg.Types.GroupInfo();
              }
              GroupInfo.MergeFrom(other.GroupInfo);
            }
            msgList_.Add(other.msgList_);
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public void MergeFrom(pb::CodedInputStream input) {
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
          #else
            uint tag;
            while ((tag = input.ReadTag()) != 0) {
            if ((tag & 7) == 4) {
              // Abort on any end group tag.
              return;
            }
            switch(tag) {
                default:
                  _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                  break;
                case 10: {
                  if (groupInfo_ == null) {
                    GroupInfo = new global::GetGroupMsgResIdl.Types.DataRes.Types.GroupMsg.Types.GroupInfo();
                  }
                  input.ReadMessage(GroupInfo);
                  break;
                }
                case 18: {
                  msgList_.AddEntriesFrom(input, _repeated_msgList_codec);
                  break;
                }
              }
            }
          #endif
          }

          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
            uint tag;
            while ((tag = input.ReadTag()) != 0) {
            if ((tag & 7) == 4) {
              // Abort on any end group tag.
              return;
            }
            switch(tag) {
                default:
                  _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                  break;
                case 10: {
                  if (groupInfo_ == null) {
                    GroupInfo = new global::GetGroupMsgResIdl.Types.DataRes.Types.GroupMsg.Types.GroupInfo();
                  }
                  input.ReadMessage(GroupInfo);
                  break;
                }
                case 18: {
                  msgList_.AddEntriesFrom(ref input, _repeated_msgList_codec);
                  break;
                }
              }
            }
          }
          #endif

          #region Nested types
          /// <summary>Container for nested types declared in the GroupMsg message type.</summary>
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public static partial class Types {
            [global::System.SerializableAttribute]
            [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
            internal sealed partial class GroupInfo : pb::IMessage<GroupInfo>
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                , pb::IBufferMessage
            #endif
            {
              private static readonly pb::MessageParser<GroupInfo> _parser = new pb::MessageParser<GroupInfo>(() => new GroupInfo());
              private pb::UnknownFieldSet _unknownFields;
              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public static pb::MessageParser<GroupInfo> Parser { get { return _parser; } }

              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public static pbr::MessageDescriptor Descriptor {
                get { return global::GetGroupMsgResIdl.Types.DataRes.Types.GroupMsg.Descriptor.NestedTypes[0]; }
              }

              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              pbr::MessageDescriptor pb::IMessage.Descriptor {
                get { return Descriptor; }
              }

              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public GroupInfo() {
                OnConstruction();
              }

              partial void OnConstruction();

              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public GroupInfo(GroupInfo other) : this() {
                groupId_ = other.groupId_;
                groupType_ = other.groupType_;
                _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
              }

              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public GroupInfo Clone() {
                return new GroupInfo(this);
              }

              /// <summary>Field number for the "groupId" field.</summary>
              public const int GroupIdFieldNumber = 1;
              private long groupId_;
              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public long GroupId {
                get { return groupId_; }
                set {
                  groupId_ = value;
                }
              }

              /// <summary>Field number for the "groupType" field.</summary>
              public const int GroupTypeFieldNumber = 20;
              private int groupType_;
              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public int GroupType {
                get { return groupType_; }
                set {
                  groupType_ = value;
                }
              }

              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public override bool Equals(object other) {
                return Equals(other as GroupInfo);
              }

              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public bool Equals(GroupInfo other) {
                if (ReferenceEquals(other, null)) {
                  return false;
                }
                if (ReferenceEquals(other, this)) {
                  return true;
                }
                if (GroupId != other.GroupId) return false;
                if (GroupType != other.GroupType) return false;
                return Equals(_unknownFields, other._unknownFields);
              }

              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public override int GetHashCode() {
                int hash = 1;
                if (GroupId != 0L) hash ^= GroupId.GetHashCode();
                if (GroupType != 0) hash ^= GroupType.GetHashCode();
                if (_unknownFields != null) {
                  hash ^= _unknownFields.GetHashCode();
                }
                return hash;
              }

              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public override string ToString() {
                return pb::JsonFormatter.ToDiagnosticString(this);
              }

              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public void WriteTo(pb::CodedOutputStream output) {
              #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                output.WriteRawMessage(this);
              #else
                if (GroupId != 0L) {
                  output.WriteRawTag(8);
                  output.WriteInt64(GroupId);
                }
                if (GroupType != 0) {
                  output.WriteRawTag(160, 1);
                  output.WriteInt32(GroupType);
                }
                if (_unknownFields != null) {
                  _unknownFields.WriteTo(output);
                }
              #endif
              }

              #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
                if (GroupId != 0L) {
                  output.WriteRawTag(8);
                  output.WriteInt64(GroupId);
                }
                if (GroupType != 0) {
                  output.WriteRawTag(160, 1);
                  output.WriteInt32(GroupType);
                }
                if (_unknownFields != null) {
                  _unknownFields.WriteTo(ref output);
                }
              }
              #endif

              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public int CalculateSize() {
                int size = 0;
                if (GroupId != 0L) {
                  size += 1 + pb::CodedOutputStream.ComputeInt64Size(GroupId);
                }
                if (GroupType != 0) {
                  size += 2 + pb::CodedOutputStream.ComputeInt32Size(GroupType);
                }
                if (_unknownFields != null) {
                  size += _unknownFields.CalculateSize();
                }
                return size;
              }

              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public void MergeFrom(GroupInfo other) {
                if (other == null) {
                  return;
                }
                if (other.GroupId != 0L) {
                  GroupId = other.GroupId;
                }
                if (other.GroupType != 0) {
                  GroupType = other.GroupType;
                }
                _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
              }

              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public void MergeFrom(pb::CodedInputStream input) {
              #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                input.ReadRawMessage(this);
              #else
                uint tag;
                while ((tag = input.ReadTag()) != 0) {
                if ((tag & 7) == 4) {
                  // Abort on any end group tag.
                  return;
                }
                switch(tag) {
                    default:
                      _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                      break;
                    case 8: {
                      GroupId = input.ReadInt64();
                      break;
                    }
                    case 160: {
                      GroupType = input.ReadInt32();
                      break;
                    }
                  }
                }
              #endif
              }

              #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
                uint tag;
                while ((tag = input.ReadTag()) != 0) {
                if ((tag & 7) == 4) {
                  // Abort on any end group tag.
                  return;
                }
                switch(tag) {
                    default:
                      _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                      break;
                    case 8: {
                      GroupId = input.ReadInt64();
                      break;
                    }
                    case 160: {
                      GroupType = input.ReadInt32();
                      break;
                    }
                  }
                }
              }
              #endif

            }

            [global::System.SerializableAttribute]
            [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
            internal sealed partial class MsgInfo : pb::IMessage<MsgInfo>
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                , pb::IBufferMessage
            #endif
            {
              private static readonly pb::MessageParser<MsgInfo> _parser = new pb::MessageParser<MsgInfo>(() => new MsgInfo());
              private pb::UnknownFieldSet _unknownFields;
              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public static pb::MessageParser<MsgInfo> Parser { get { return _parser; } }

              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public static pbr::MessageDescriptor Descriptor {
                get { return global::GetGroupMsgResIdl.Types.DataRes.Types.GroupMsg.Descriptor.NestedTypes[1]; }
              }

              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              pbr::MessageDescriptor pb::IMessage.Descriptor {
                get { return Descriptor; }
              }

              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public MsgInfo() {
                OnConstruction();
              }

              partial void OnConstruction();

              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public MsgInfo(MsgInfo other) : this() {
                msgId_ = other.msgId_;
                msgType_ = other.msgType_;
                content_ = other.content_;
                createTime_ = other.createTime_;
                userInfo_ = other.userInfo_ != null ? other.userInfo_.Clone() : null;
                _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
              }

              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public MsgInfo Clone() {
                return new MsgInfo(this);
              }

              /// <summary>Field number for the "msgId" field.</summary>
              public const int MsgIdFieldNumber = 1;
              private long msgId_;
              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public long MsgId {
                get { return msgId_; }
                set {
                  msgId_ = value;
                }
              }

              /// <summary>Field number for the "msgType" field.</summary>
              public const int MsgTypeFieldNumber = 3;
              private int msgType_;
              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public int MsgType {
                get { return msgType_; }
                set {
                  msgType_ = value;
                }
              }

              /// <summary>Field number for the "content" field.</summary>
              public const int ContentFieldNumber = 5;
              private string content_ = "";
              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public string Content {
                get { return content_; }
                set {
                  content_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
                }
              }

              /// <summary>Field number for the "createTime" field.</summary>
              public const int CreateTimeFieldNumber = 8;
              private int createTime_;
              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public int CreateTime {
                get { return createTime_; }
                set {
                  createTime_ = value;
                }
              }

              /// <summary>Field number for the "userInfo" field.</summary>
              public const int UserInfoFieldNumber = 10;
              private global::GetGroupMsgResIdl.Types.DataRes.Types.GroupMsg.Types.MsgInfo.Types.UserInfo userInfo_;
              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public global::GetGroupMsgResIdl.Types.DataRes.Types.GroupMsg.Types.MsgInfo.Types.UserInfo UserInfo {
                get { return userInfo_; }
                set {
                  userInfo_ = value;
                }
              }

              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public override bool Equals(object other) {
                return Equals(other as MsgInfo);
              }

              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public bool Equals(MsgInfo other) {
                if (ReferenceEquals(other, null)) {
                  return false;
                }
                if (ReferenceEquals(other, this)) {
                  return true;
                }
                if (MsgId != other.MsgId) return false;
                if (MsgType != other.MsgType) return false;
                if (Content != other.Content) return false;
                if (CreateTime != other.CreateTime) return false;
                if (!object.Equals(UserInfo, other.UserInfo)) return false;
                return Equals(_unknownFields, other._unknownFields);
              }

              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public override int GetHashCode() {
                int hash = 1;
                if (MsgId != 0L) hash ^= MsgId.GetHashCode();
                if (MsgType != 0) hash ^= MsgType.GetHashCode();
                if (Content.Length != 0) hash ^= Content.GetHashCode();
                if (CreateTime != 0) hash ^= CreateTime.GetHashCode();
                if (userInfo_ != null) hash ^= UserInfo.GetHashCode();
                if (_unknownFields != null) {
                  hash ^= _unknownFields.GetHashCode();
                }
                return hash;
              }

              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public override string ToString() {
                return pb::JsonFormatter.ToDiagnosticString(this);
              }

              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public void WriteTo(pb::CodedOutputStream output) {
              #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                output.WriteRawMessage(this);
              #else
                if (MsgId != 0L) {
                  output.WriteRawTag(8);
                  output.WriteInt64(MsgId);
                }
                if (MsgType != 0) {
                  output.WriteRawTag(24);
                  output.WriteInt32(MsgType);
                }
                if (Content.Length != 0) {
                  output.WriteRawTag(42);
                  output.WriteString(Content);
                }
                if (CreateTime != 0) {
                  output.WriteRawTag(64);
                  output.WriteInt32(CreateTime);
                }
                if (userInfo_ != null) {
                  output.WriteRawTag(82);
                  output.WriteMessage(UserInfo);
                }
                if (_unknownFields != null) {
                  _unknownFields.WriteTo(output);
                }
              #endif
              }

              #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
                if (MsgId != 0L) {
                  output.WriteRawTag(8);
                  output.WriteInt64(MsgId);
                }
                if (MsgType != 0) {
                  output.WriteRawTag(24);
                  output.WriteInt32(MsgType);
                }
                if (Content.Length != 0) {
                  output.WriteRawTag(42);
                  output.WriteString(Content);
                }
                if (CreateTime != 0) {
                  output.WriteRawTag(64);
                  output.WriteInt32(CreateTime);
                }
                if (userInfo_ != null) {
                  output.WriteRawTag(82);
                  output.WriteMessage(UserInfo);
                }
                if (_unknownFields != null) {
                  _unknownFields.WriteTo(ref output);
                }
              }
              #endif

              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public int CalculateSize() {
                int size = 0;
                if (MsgId != 0L) {
                  size += 1 + pb::CodedOutputStream.ComputeInt64Size(MsgId);
                }
                if (MsgType != 0) {
                  size += 1 + pb::CodedOutputStream.ComputeInt32Size(MsgType);
                }
                if (Content.Length != 0) {
                  size += 1 + pb::CodedOutputStream.ComputeStringSize(Content);
                }
                if (CreateTime != 0) {
                  size += 1 + pb::CodedOutputStream.ComputeInt32Size(CreateTime);
                }
                if (userInfo_ != null) {
                  size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserInfo);
                }
                if (_unknownFields != null) {
                  size += _unknownFields.CalculateSize();
                }
                return size;
              }

              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public void MergeFrom(MsgInfo other) {
                if (other == null) {
                  return;
                }
                if (other.MsgId != 0L) {
                  MsgId = other.MsgId;
                }
                if (other.MsgType != 0) {
                  MsgType = other.MsgType;
                }
                if (other.Content.Length != 0) {
                  Content = other.Content;
                }
                if (other.CreateTime != 0) {
                  CreateTime = other.CreateTime;
                }
                if (other.userInfo_ != null) {
                  if (userInfo_ == null) {
                    UserInfo = new global::GetGroupMsgResIdl.Types.DataRes.Types.GroupMsg.Types.MsgInfo.Types.UserInfo();
                  }
                  UserInfo.MergeFrom(other.UserInfo);
                }
                _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
              }

              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public void MergeFrom(pb::CodedInputStream input) {
              #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                input.ReadRawMessage(this);
              #else
                uint tag;
                while ((tag = input.ReadTag()) != 0) {
                if ((tag & 7) == 4) {
                  // Abort on any end group tag.
                  return;
                }
                switch(tag) {
                    default:
                      _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                      break;
                    case 8: {
                      MsgId = input.ReadInt64();
                      break;
                    }
                    case 24: {
                      MsgType = input.ReadInt32();
                      break;
                    }
                    case 42: {
                      Content = input.ReadString();
                      break;
                    }
                    case 64: {
                      CreateTime = input.ReadInt32();
                      break;
                    }
                    case 82: {
                      if (userInfo_ == null) {
                        UserInfo = new global::GetGroupMsgResIdl.Types.DataRes.Types.GroupMsg.Types.MsgInfo.Types.UserInfo();
                      }
                      input.ReadMessage(UserInfo);
                      break;
                    }
                  }
                }
              #endif
              }

              #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
                uint tag;
                while ((tag = input.ReadTag()) != 0) {
                if ((tag & 7) == 4) {
                  // Abort on any end group tag.
                  return;
                }
                switch(tag) {
                    default:
                      _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                      break;
                    case 8: {
                      MsgId = input.ReadInt64();
                      break;
                    }
                    case 24: {
                      MsgType = input.ReadInt32();
                      break;
                    }
                    case 42: {
                      Content = input.ReadString();
                      break;
                    }
                    case 64: {
                      CreateTime = input.ReadInt32();
                      break;
                    }
                    case 82: {
                      if (userInfo_ == null) {
                        UserInfo = new global::GetGroupMsgResIdl.Types.DataRes.Types.GroupMsg.Types.MsgInfo.Types.UserInfo();
                      }
                      input.ReadMessage(UserInfo);
                      break;
                    }
                  }
                }
              }
              #endif

              #region Nested types
              /// <summary>Container for nested types declared in the MsgInfo message type.</summary>
              [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
              [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
              public static partial class Types {
                [global::System.SerializableAttribute]
                [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
                internal sealed partial class UserInfo : pb::IMessage<UserInfo>
                #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                    , pb::IBufferMessage
                #endif
                {
                  private static readonly pb::MessageParser<UserInfo> _parser = new pb::MessageParser<UserInfo>(() => new UserInfo());
                  private pb::UnknownFieldSet _unknownFields;
                  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                  public static pb::MessageParser<UserInfo> Parser { get { return _parser; } }

                  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                  public static pbr::MessageDescriptor Descriptor {
                    get { return global::GetGroupMsgResIdl.Types.DataRes.Types.GroupMsg.Types.MsgInfo.Descriptor.NestedTypes[0]; }
                  }

                  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                  pbr::MessageDescriptor pb::IMessage.Descriptor {
                    get { return Descriptor; }
                  }

                  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                  public UserInfo() {
                    OnConstruction();
                  }

                  partial void OnConstruction();

                  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                  public UserInfo(UserInfo other) : this() {
                    userId_ = other.userId_;
                    userName_ = other.userName_;
                    portrait_ = other.portrait_;
                    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
                  }

                  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                  public UserInfo Clone() {
                    return new UserInfo(this);
                  }

                  /// <summary>Field number for the "userId" field.</summary>
                  public const int UserIdFieldNumber = 1;
                  private long userId_;
                  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                  public long UserId {
                    get { return userId_; }
                    set {
                      userId_ = value;
                    }
                  }

                  /// <summary>Field number for the "userName" field.</summary>
                  public const int UserNameFieldNumber = 2;
                  private string userName_ = "";
                  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                  public string UserName {
                    get { return userName_; }
                    set {
                      userName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
                    }
                  }

                  /// <summary>Field number for the "portrait" field.</summary>
                  public const int PortraitFieldNumber = 4;
                  private string portrait_ = "";
                  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                  public string Portrait {
                    get { return portrait_; }
                    set {
                      portrait_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
                    }
                  }

                  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                  public override bool Equals(object other) {
                    return Equals(other as UserInfo);
                  }

                  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                  public bool Equals(UserInfo other) {
                    if (ReferenceEquals(other, null)) {
                      return false;
                    }
                    if (ReferenceEquals(other, this)) {
                      return true;
                    }
                    if (UserId != other.UserId) return false;
                    if (UserName != other.UserName) return false;
                    if (Portrait != other.Portrait) return false;
                    return Equals(_unknownFields, other._unknownFields);
                  }

                  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                  public override int GetHashCode() {
                    int hash = 1;
                    if (UserId != 0L) hash ^= UserId.GetHashCode();
                    if (UserName.Length != 0) hash ^= UserName.GetHashCode();
                    if (Portrait.Length != 0) hash ^= Portrait.GetHashCode();
                    if (_unknownFields != null) {
                      hash ^= _unknownFields.GetHashCode();
                    }
                    return hash;
                  }

                  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                  public override string ToString() {
                    return pb::JsonFormatter.ToDiagnosticString(this);
                  }

                  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                  public void WriteTo(pb::CodedOutputStream output) {
                  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                    output.WriteRawMessage(this);
                  #else
                    if (UserId != 0L) {
                      output.WriteRawTag(8);
                      output.WriteInt64(UserId);
                    }
                    if (UserName.Length != 0) {
                      output.WriteRawTag(18);
                      output.WriteString(UserName);
                    }
                    if (Portrait.Length != 0) {
                      output.WriteRawTag(34);
                      output.WriteString(Portrait);
                    }
                    if (_unknownFields != null) {
                      _unknownFields.WriteTo(output);
                    }
                  #endif
                  }

                  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
                    if (UserId != 0L) {
                      output.WriteRawTag(8);
                      output.WriteInt64(UserId);
                    }
                    if (UserName.Length != 0) {
                      output.WriteRawTag(18);
                      output.WriteString(UserName);
                    }
                    if (Portrait.Length != 0) {
                      output.WriteRawTag(34);
                      output.WriteString(Portrait);
                    }
                    if (_unknownFields != null) {
                      _unknownFields.WriteTo(ref output);
                    }
                  }
                  #endif

                  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                  public int CalculateSize() {
                    int size = 0;
                    if (UserId != 0L) {
                      size += 1 + pb::CodedOutputStream.ComputeInt64Size(UserId);
                    }
                    if (UserName.Length != 0) {
                      size += 1 + pb::CodedOutputStream.ComputeStringSize(UserName);
                    }
                    if (Portrait.Length != 0) {
                      size += 1 + pb::CodedOutputStream.ComputeStringSize(Portrait);
                    }
                    if (_unknownFields != null) {
                      size += _unknownFields.CalculateSize();
                    }
                    return size;
                  }

                  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                  public void MergeFrom(UserInfo other) {
                    if (other == null) {
                      return;
                    }
                    if (other.UserId != 0L) {
                      UserId = other.UserId;
                    }
                    if (other.UserName.Length != 0) {
                      UserName = other.UserName;
                    }
                    if (other.Portrait.Length != 0) {
                      Portrait = other.Portrait;
                    }
                    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
                  }

                  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                  public void MergeFrom(pb::CodedInputStream input) {
                  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                    input.ReadRawMessage(this);
                  #else
                    uint tag;
                    while ((tag = input.ReadTag()) != 0) {
                    if ((tag & 7) == 4) {
                      // Abort on any end group tag.
                      return;
                    }
                    switch(tag) {
                        default:
                          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                          break;
                        case 8: {
                          UserId = input.ReadInt64();
                          break;
                        }
                        case 18: {
                          UserName = input.ReadString();
                          break;
                        }
                        case 34: {
                          Portrait = input.ReadString();
                          break;
                        }
                      }
                    }
                  #endif
                  }

                  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
                    uint tag;
                    while ((tag = input.ReadTag()) != 0) {
                    if ((tag & 7) == 4) {
                      // Abort on any end group tag.
                      return;
                    }
                    switch(tag) {
                        default:
                          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                          break;
                        case 8: {
                          UserId = input.ReadInt64();
                          break;
                        }
                        case 18: {
                          UserName = input.ReadString();
                          break;
                        }
                        case 34: {
                          Portrait = input.ReadString();
                          break;
                        }
                      }
                    }
                  }
                  #endif

                }

              }
              #endregion

            }

          }
          #endregion

        }

      }
      #endregion

    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
