// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ForumList.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ForumList.proto</summary>
public static partial class ForumListReflection {

  #region Descriptor
  /// <summary>File descriptor for ForumList.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ForumListReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg9Gb3J1bUxpc3QucHJvdG8ibQoJRm9ydW1MaXN0EhAKCGZvcnVtX2lkGAEg",
          "ASgDEhIKCmZvcnVtX25hbWUYAiABKAkSFAoMbWVtYmVyX2NvdW50GAQgASgF",
          "EhAKCHBvc3RfbnVtGAcgASgDEhIKCnRocmVhZF9udW0YCCABKANiBnByb3Rv",
          "Mw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ForumList), global::ForumList.Parser, new[]{ "ForumId", "ForumName", "MemberCount", "PostNum", "ThreadNum" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.SerializableAttribute]
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ForumList : pb::IMessage<ForumList>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ForumList> _parser = new pb::MessageParser<ForumList>(() => new ForumList());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ForumList> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ForumListReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ForumList() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ForumList(ForumList other) : this() {
    forumId_ = other.forumId_;
    forumName_ = other.forumName_;
    memberCount_ = other.memberCount_;
    postNum_ = other.postNum_;
    threadNum_ = other.threadNum_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ForumList Clone() {
    return new ForumList(this);
  }

  /// <summary>Field number for the "forum_id" field.</summary>
  public const int ForumIdFieldNumber = 1;
  private long forumId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long ForumId {
    get { return forumId_; }
    set {
      forumId_ = value;
    }
  }

  /// <summary>Field number for the "forum_name" field.</summary>
  public const int ForumNameFieldNumber = 2;
  private string forumName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ForumName {
    get { return forumName_; }
    set {
      forumName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "member_count" field.</summary>
  public const int MemberCountFieldNumber = 4;
  private int memberCount_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int MemberCount {
    get { return memberCount_; }
    set {
      memberCount_ = value;
    }
  }

  /// <summary>Field number for the "post_num" field.</summary>
  public const int PostNumFieldNumber = 7;
  private long postNum_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long PostNum {
    get { return postNum_; }
    set {
      postNum_ = value;
    }
  }

  /// <summary>Field number for the "thread_num" field.</summary>
  public const int ThreadNumFieldNumber = 8;
  private long threadNum_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long ThreadNum {
    get { return threadNum_; }
    set {
      threadNum_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ForumList);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ForumList other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ForumId != other.ForumId) return false;
    if (ForumName != other.ForumName) return false;
    if (MemberCount != other.MemberCount) return false;
    if (PostNum != other.PostNum) return false;
    if (ThreadNum != other.ThreadNum) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (ForumId != 0L) hash ^= ForumId.GetHashCode();
    if (ForumName.Length != 0) hash ^= ForumName.GetHashCode();
    if (MemberCount != 0) hash ^= MemberCount.GetHashCode();
    if (PostNum != 0L) hash ^= PostNum.GetHashCode();
    if (ThreadNum != 0L) hash ^= ThreadNum.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (ForumId != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(ForumId);
    }
    if (ForumName.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(ForumName);
    }
    if (MemberCount != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(MemberCount);
    }
    if (PostNum != 0L) {
      output.WriteRawTag(56);
      output.WriteInt64(PostNum);
    }
    if (ThreadNum != 0L) {
      output.WriteRawTag(64);
      output.WriteInt64(ThreadNum);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (ForumId != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(ForumId);
    }
    if (ForumName.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(ForumName);
    }
    if (MemberCount != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(MemberCount);
    }
    if (PostNum != 0L) {
      output.WriteRawTag(56);
      output.WriteInt64(PostNum);
    }
    if (ThreadNum != 0L) {
      output.WriteRawTag(64);
      output.WriteInt64(ThreadNum);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (ForumId != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(ForumId);
    }
    if (ForumName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ForumName);
    }
    if (MemberCount != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(MemberCount);
    }
    if (PostNum != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(PostNum);
    }
    if (ThreadNum != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(ThreadNum);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ForumList other) {
    if (other == null) {
      return;
    }
    if (other.ForumId != 0L) {
      ForumId = other.ForumId;
    }
    if (other.ForumName.Length != 0) {
      ForumName = other.ForumName;
    }
    if (other.MemberCount != 0) {
      MemberCount = other.MemberCount;
    }
    if (other.PostNum != 0L) {
      PostNum = other.PostNum;
    }
    if (other.ThreadNum != 0L) {
      ThreadNum = other.ThreadNum;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          ForumId = input.ReadInt64();
          break;
        }
        case 18: {
          ForumName = input.ReadString();
          break;
        }
        case 32: {
          MemberCount = input.ReadInt32();
          break;
        }
        case 56: {
          PostNum = input.ReadInt64();
          break;
        }
        case 64: {
          ThreadNum = input.ReadInt64();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          ForumId = input.ReadInt64();
          break;
        }
        case 18: {
          ForumName = input.ReadString();
          break;
        }
        case 32: {
          MemberCount = input.ReadInt32();
          break;
        }
        case 56: {
          PostNum = input.ReadInt64();
          break;
        }
        case 64: {
          ThreadNum = input.ReadInt64();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
