// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Lcm.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Lcm.proto</summary>
public static partial class LcmReflection {

  #region Descriptor
  /// <summary>File descriptor for Lcm.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static LcmReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CglMY20ucHJvdG8i1QEKBkNvbW1vbhIMCgRjdWlkGAEgASgJEg4KBmRldmlj",
          "ZRgCIAEoCRISCgpvc192ZXJzaW9uGAMgASgJEhMKC21hbnVmYWN0dXJlGAQg",
          "ASgJEhIKCm1vZGVsX3R5cGUYBSABKAkSDgoGYXBwX2lkGAYgASgJEhMKC2Fw",
          "cF92ZXJzaW9uGAcgASgJEhMKC3Nka192ZXJzaW9uGAggASgJEg8KB25ldHdv",
          "cmsYCSABKAkSEwoLcm9tX3ZlcnNpb24YCiABKAkSEAoIdXNlcl9rZXkYCyAB",
          "KAkiKwoJTGNtTm90aWZ5Eg4KBmxvZ19pZBgBIAEoAxIOCgZhY3Rpb24YAiAB",
          "KAUijgEKCkxjbVJlcXVlc3QSDgoGbG9nX2lkGAEgASgDEg0KBXRva2VuGAIg",
          "ASgJEhcKBmNvbW1vbhgDIAEoCzIHLkNvbW1vbhIRCgl0aW1lc3RhbXAYBCAB",
          "KAMSDgoGYWN0aW9uGAUgASgFEhIKCnN0YXJ0X3R5cGUYBiABKAUSEQoJY29u",
          "bl90eXBlGAcgASgFInMKC0xjbVJlc3BvbnNlEg4KBmxvZ19pZBgBIAEoAxIS",
          "CgplcnJvcl9jb2RlGAIgASgFEhEKCWVycm9yX21zZxgDIAEoCRIYChBuZXh0",
          "X2ludGVydmFsX21zGAQgASgDEhMKC3NlcnZlcl9pbmZvGAUgASgJIm8KB1Jw",
          "Y0RhdGESIAoLbGNtX3JlcXVlc3QYASABKAsyCy5MY21SZXF1ZXN0EiIKDGxj",
          "bV9yZXNwb25zZRgCIAEoCzIMLkxjbVJlc3BvbnNlEh4KCmxjbV9ub3RpZnkY",
          "AyABKAsyCi5MY21Ob3RpZnlCAkgDYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Common), global::Common.Parser, new[]{ "Cuid", "Device", "OsVersion", "Manufacture", "ModelType", "AppId", "AppVersion", "SdkVersion", "Network", "RomVersion", "UserKey" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::LcmNotify), global::LcmNotify.Parser, new[]{ "LogId", "Action" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::LcmRequest), global::LcmRequest.Parser, new[]{ "LogId", "Token", "Common", "Timestamp", "Action", "StartType", "ConnType" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::LcmResponse), global::LcmResponse.Parser, new[]{ "LogId", "ErrorCode", "ErrorMsg", "NextIntervalMs", "ServerInfo" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::RpcData), global::RpcData.Parser, new[]{ "LcmRequest", "LcmResponse", "LcmNotify" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.SerializableAttribute]
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class Common : pb::IMessage<Common>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Common> _parser = new pb::MessageParser<Common>(() => new Common());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Common> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::LcmReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Common() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Common(Common other) : this() {
    cuid_ = other.cuid_;
    device_ = other.device_;
    osVersion_ = other.osVersion_;
    manufacture_ = other.manufacture_;
    modelType_ = other.modelType_;
    appId_ = other.appId_;
    appVersion_ = other.appVersion_;
    sdkVersion_ = other.sdkVersion_;
    network_ = other.network_;
    romVersion_ = other.romVersion_;
    userKey_ = other.userKey_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Common Clone() {
    return new Common(this);
  }

  /// <summary>Field number for the "cuid" field.</summary>
  public const int CuidFieldNumber = 1;
  private string cuid_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Cuid {
    get { return cuid_; }
    set {
      cuid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "device" field.</summary>
  public const int DeviceFieldNumber = 2;
  private string device_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Device {
    get { return device_; }
    set {
      device_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "os_version" field.</summary>
  public const int OsVersionFieldNumber = 3;
  private string osVersion_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string OsVersion {
    get { return osVersion_; }
    set {
      osVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "manufacture" field.</summary>
  public const int ManufactureFieldNumber = 4;
  private string manufacture_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Manufacture {
    get { return manufacture_; }
    set {
      manufacture_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "model_type" field.</summary>
  public const int ModelTypeFieldNumber = 5;
  private string modelType_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ModelType {
    get { return modelType_; }
    set {
      modelType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "app_id" field.</summary>
  public const int AppIdFieldNumber = 6;
  private string appId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string AppId {
    get { return appId_; }
    set {
      appId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "app_version" field.</summary>
  public const int AppVersionFieldNumber = 7;
  private string appVersion_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string AppVersion {
    get { return appVersion_; }
    set {
      appVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "sdk_version" field.</summary>
  public const int SdkVersionFieldNumber = 8;
  private string sdkVersion_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string SdkVersion {
    get { return sdkVersion_; }
    set {
      sdkVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "network" field.</summary>
  public const int NetworkFieldNumber = 9;
  private string network_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Network {
    get { return network_; }
    set {
      network_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "rom_version" field.</summary>
  public const int RomVersionFieldNumber = 10;
  private string romVersion_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string RomVersion {
    get { return romVersion_; }
    set {
      romVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "user_key" field.</summary>
  public const int UserKeyFieldNumber = 11;
  private string userKey_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string UserKey {
    get { return userKey_; }
    set {
      userKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Common);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Common other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Cuid != other.Cuid) return false;
    if (Device != other.Device) return false;
    if (OsVersion != other.OsVersion) return false;
    if (Manufacture != other.Manufacture) return false;
    if (ModelType != other.ModelType) return false;
    if (AppId != other.AppId) return false;
    if (AppVersion != other.AppVersion) return false;
    if (SdkVersion != other.SdkVersion) return false;
    if (Network != other.Network) return false;
    if (RomVersion != other.RomVersion) return false;
    if (UserKey != other.UserKey) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Cuid.Length != 0) hash ^= Cuid.GetHashCode();
    if (Device.Length != 0) hash ^= Device.GetHashCode();
    if (OsVersion.Length != 0) hash ^= OsVersion.GetHashCode();
    if (Manufacture.Length != 0) hash ^= Manufacture.GetHashCode();
    if (ModelType.Length != 0) hash ^= ModelType.GetHashCode();
    if (AppId.Length != 0) hash ^= AppId.GetHashCode();
    if (AppVersion.Length != 0) hash ^= AppVersion.GetHashCode();
    if (SdkVersion.Length != 0) hash ^= SdkVersion.GetHashCode();
    if (Network.Length != 0) hash ^= Network.GetHashCode();
    if (RomVersion.Length != 0) hash ^= RomVersion.GetHashCode();
    if (UserKey.Length != 0) hash ^= UserKey.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Cuid.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Cuid);
    }
    if (Device.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Device);
    }
    if (OsVersion.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(OsVersion);
    }
    if (Manufacture.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(Manufacture);
    }
    if (ModelType.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(ModelType);
    }
    if (AppId.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(AppId);
    }
    if (AppVersion.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(AppVersion);
    }
    if (SdkVersion.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(SdkVersion);
    }
    if (Network.Length != 0) {
      output.WriteRawTag(74);
      output.WriteString(Network);
    }
    if (RomVersion.Length != 0) {
      output.WriteRawTag(82);
      output.WriteString(RomVersion);
    }
    if (UserKey.Length != 0) {
      output.WriteRawTag(90);
      output.WriteString(UserKey);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Cuid.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Cuid);
    }
    if (Device.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Device);
    }
    if (OsVersion.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(OsVersion);
    }
    if (Manufacture.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(Manufacture);
    }
    if (ModelType.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(ModelType);
    }
    if (AppId.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(AppId);
    }
    if (AppVersion.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(AppVersion);
    }
    if (SdkVersion.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(SdkVersion);
    }
    if (Network.Length != 0) {
      output.WriteRawTag(74);
      output.WriteString(Network);
    }
    if (RomVersion.Length != 0) {
      output.WriteRawTag(82);
      output.WriteString(RomVersion);
    }
    if (UserKey.Length != 0) {
      output.WriteRawTag(90);
      output.WriteString(UserKey);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Cuid.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Cuid);
    }
    if (Device.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Device);
    }
    if (OsVersion.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(OsVersion);
    }
    if (Manufacture.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Manufacture);
    }
    if (ModelType.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ModelType);
    }
    if (AppId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AppId);
    }
    if (AppVersion.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AppVersion);
    }
    if (SdkVersion.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(SdkVersion);
    }
    if (Network.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Network);
    }
    if (RomVersion.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(RomVersion);
    }
    if (UserKey.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(UserKey);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Common other) {
    if (other == null) {
      return;
    }
    if (other.Cuid.Length != 0) {
      Cuid = other.Cuid;
    }
    if (other.Device.Length != 0) {
      Device = other.Device;
    }
    if (other.OsVersion.Length != 0) {
      OsVersion = other.OsVersion;
    }
    if (other.Manufacture.Length != 0) {
      Manufacture = other.Manufacture;
    }
    if (other.ModelType.Length != 0) {
      ModelType = other.ModelType;
    }
    if (other.AppId.Length != 0) {
      AppId = other.AppId;
    }
    if (other.AppVersion.Length != 0) {
      AppVersion = other.AppVersion;
    }
    if (other.SdkVersion.Length != 0) {
      SdkVersion = other.SdkVersion;
    }
    if (other.Network.Length != 0) {
      Network = other.Network;
    }
    if (other.RomVersion.Length != 0) {
      RomVersion = other.RomVersion;
    }
    if (other.UserKey.Length != 0) {
      UserKey = other.UserKey;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Cuid = input.ReadString();
          break;
        }
        case 18: {
          Device = input.ReadString();
          break;
        }
        case 26: {
          OsVersion = input.ReadString();
          break;
        }
        case 34: {
          Manufacture = input.ReadString();
          break;
        }
        case 42: {
          ModelType = input.ReadString();
          break;
        }
        case 50: {
          AppId = input.ReadString();
          break;
        }
        case 58: {
          AppVersion = input.ReadString();
          break;
        }
        case 66: {
          SdkVersion = input.ReadString();
          break;
        }
        case 74: {
          Network = input.ReadString();
          break;
        }
        case 82: {
          RomVersion = input.ReadString();
          break;
        }
        case 90: {
          UserKey = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Cuid = input.ReadString();
          break;
        }
        case 18: {
          Device = input.ReadString();
          break;
        }
        case 26: {
          OsVersion = input.ReadString();
          break;
        }
        case 34: {
          Manufacture = input.ReadString();
          break;
        }
        case 42: {
          ModelType = input.ReadString();
          break;
        }
        case 50: {
          AppId = input.ReadString();
          break;
        }
        case 58: {
          AppVersion = input.ReadString();
          break;
        }
        case 66: {
          SdkVersion = input.ReadString();
          break;
        }
        case 74: {
          Network = input.ReadString();
          break;
        }
        case 82: {
          RomVersion = input.ReadString();
          break;
        }
        case 90: {
          UserKey = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.SerializableAttribute]
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class LcmNotify : pb::IMessage<LcmNotify>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<LcmNotify> _parser = new pb::MessageParser<LcmNotify>(() => new LcmNotify());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<LcmNotify> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::LcmReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LcmNotify() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LcmNotify(LcmNotify other) : this() {
    logId_ = other.logId_;
    action_ = other.action_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LcmNotify Clone() {
    return new LcmNotify(this);
  }

  /// <summary>Field number for the "log_id" field.</summary>
  public const int LogIdFieldNumber = 1;
  private long logId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long LogId {
    get { return logId_; }
    set {
      logId_ = value;
    }
  }

  /// <summary>Field number for the "action" field.</summary>
  public const int ActionFieldNumber = 2;
  private int action_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Action {
    get { return action_; }
    set {
      action_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as LcmNotify);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(LcmNotify other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (LogId != other.LogId) return false;
    if (Action != other.Action) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (LogId != 0L) hash ^= LogId.GetHashCode();
    if (Action != 0) hash ^= Action.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (LogId != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(LogId);
    }
    if (Action != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Action);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (LogId != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(LogId);
    }
    if (Action != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Action);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (LogId != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(LogId);
    }
    if (Action != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Action);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(LcmNotify other) {
    if (other == null) {
      return;
    }
    if (other.LogId != 0L) {
      LogId = other.LogId;
    }
    if (other.Action != 0) {
      Action = other.Action;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          LogId = input.ReadInt64();
          break;
        }
        case 16: {
          Action = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          LogId = input.ReadInt64();
          break;
        }
        case 16: {
          Action = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.SerializableAttribute]
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class LcmRequest : pb::IMessage<LcmRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<LcmRequest> _parser = new pb::MessageParser<LcmRequest>(() => new LcmRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<LcmRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::LcmReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LcmRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LcmRequest(LcmRequest other) : this() {
    logId_ = other.logId_;
    token_ = other.token_;
    common_ = other.common_ != null ? other.common_.Clone() : null;
    timestamp_ = other.timestamp_;
    action_ = other.action_;
    startType_ = other.startType_;
    connType_ = other.connType_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LcmRequest Clone() {
    return new LcmRequest(this);
  }

  /// <summary>Field number for the "log_id" field.</summary>
  public const int LogIdFieldNumber = 1;
  private long logId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long LogId {
    get { return logId_; }
    set {
      logId_ = value;
    }
  }

  /// <summary>Field number for the "token" field.</summary>
  public const int TokenFieldNumber = 2;
  private string token_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Token {
    get { return token_; }
    set {
      token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "common" field.</summary>
  public const int CommonFieldNumber = 3;
  private global::Common common_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Common Common {
    get { return common_; }
    set {
      common_ = value;
    }
  }

  /// <summary>Field number for the "timestamp" field.</summary>
  public const int TimestampFieldNumber = 4;
  private long timestamp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Timestamp {
    get { return timestamp_; }
    set {
      timestamp_ = value;
    }
  }

  /// <summary>Field number for the "action" field.</summary>
  public const int ActionFieldNumber = 5;
  private int action_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Action {
    get { return action_; }
    set {
      action_ = value;
    }
  }

  /// <summary>Field number for the "start_type" field.</summary>
  public const int StartTypeFieldNumber = 6;
  private int startType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int StartType {
    get { return startType_; }
    set {
      startType_ = value;
    }
  }

  /// <summary>Field number for the "conn_type" field.</summary>
  public const int ConnTypeFieldNumber = 7;
  private int connType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ConnType {
    get { return connType_; }
    set {
      connType_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as LcmRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(LcmRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (LogId != other.LogId) return false;
    if (Token != other.Token) return false;
    if (!object.Equals(Common, other.Common)) return false;
    if (Timestamp != other.Timestamp) return false;
    if (Action != other.Action) return false;
    if (StartType != other.StartType) return false;
    if (ConnType != other.ConnType) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (LogId != 0L) hash ^= LogId.GetHashCode();
    if (Token.Length != 0) hash ^= Token.GetHashCode();
    if (common_ != null) hash ^= Common.GetHashCode();
    if (Timestamp != 0L) hash ^= Timestamp.GetHashCode();
    if (Action != 0) hash ^= Action.GetHashCode();
    if (StartType != 0) hash ^= StartType.GetHashCode();
    if (ConnType != 0) hash ^= ConnType.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (LogId != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(LogId);
    }
    if (Token.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Token);
    }
    if (common_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(Common);
    }
    if (Timestamp != 0L) {
      output.WriteRawTag(32);
      output.WriteInt64(Timestamp);
    }
    if (Action != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(Action);
    }
    if (StartType != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(StartType);
    }
    if (ConnType != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(ConnType);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (LogId != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(LogId);
    }
    if (Token.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Token);
    }
    if (common_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(Common);
    }
    if (Timestamp != 0L) {
      output.WriteRawTag(32);
      output.WriteInt64(Timestamp);
    }
    if (Action != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(Action);
    }
    if (StartType != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(StartType);
    }
    if (ConnType != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(ConnType);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (LogId != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(LogId);
    }
    if (Token.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
    }
    if (common_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Common);
    }
    if (Timestamp != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Timestamp);
    }
    if (Action != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Action);
    }
    if (StartType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(StartType);
    }
    if (ConnType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ConnType);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(LcmRequest other) {
    if (other == null) {
      return;
    }
    if (other.LogId != 0L) {
      LogId = other.LogId;
    }
    if (other.Token.Length != 0) {
      Token = other.Token;
    }
    if (other.common_ != null) {
      if (common_ == null) {
        Common = new global::Common();
      }
      Common.MergeFrom(other.Common);
    }
    if (other.Timestamp != 0L) {
      Timestamp = other.Timestamp;
    }
    if (other.Action != 0) {
      Action = other.Action;
    }
    if (other.StartType != 0) {
      StartType = other.StartType;
    }
    if (other.ConnType != 0) {
      ConnType = other.ConnType;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          LogId = input.ReadInt64();
          break;
        }
        case 18: {
          Token = input.ReadString();
          break;
        }
        case 26: {
          if (common_ == null) {
            Common = new global::Common();
          }
          input.ReadMessage(Common);
          break;
        }
        case 32: {
          Timestamp = input.ReadInt64();
          break;
        }
        case 40: {
          Action = input.ReadInt32();
          break;
        }
        case 48: {
          StartType = input.ReadInt32();
          break;
        }
        case 56: {
          ConnType = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          LogId = input.ReadInt64();
          break;
        }
        case 18: {
          Token = input.ReadString();
          break;
        }
        case 26: {
          if (common_ == null) {
            Common = new global::Common();
          }
          input.ReadMessage(Common);
          break;
        }
        case 32: {
          Timestamp = input.ReadInt64();
          break;
        }
        case 40: {
          Action = input.ReadInt32();
          break;
        }
        case 48: {
          StartType = input.ReadInt32();
          break;
        }
        case 56: {
          ConnType = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.SerializableAttribute]
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class LcmResponse : pb::IMessage<LcmResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<LcmResponse> _parser = new pb::MessageParser<LcmResponse>(() => new LcmResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<LcmResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::LcmReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LcmResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LcmResponse(LcmResponse other) : this() {
    logId_ = other.logId_;
    errorCode_ = other.errorCode_;
    errorMsg_ = other.errorMsg_;
    nextIntervalMs_ = other.nextIntervalMs_;
    serverInfo_ = other.serverInfo_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LcmResponse Clone() {
    return new LcmResponse(this);
  }

  /// <summary>Field number for the "log_id" field.</summary>
  public const int LogIdFieldNumber = 1;
  private long logId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long LogId {
    get { return logId_; }
    set {
      logId_ = value;
    }
  }

  /// <summary>Field number for the "error_code" field.</summary>
  public const int ErrorCodeFieldNumber = 2;
  private int errorCode_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ErrorCode {
    get { return errorCode_; }
    set {
      errorCode_ = value;
    }
  }

  /// <summary>Field number for the "error_msg" field.</summary>
  public const int ErrorMsgFieldNumber = 3;
  private string errorMsg_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ErrorMsg {
    get { return errorMsg_; }
    set {
      errorMsg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "next_interval_ms" field.</summary>
  public const int NextIntervalMsFieldNumber = 4;
  private long nextIntervalMs_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long NextIntervalMs {
    get { return nextIntervalMs_; }
    set {
      nextIntervalMs_ = value;
    }
  }

  /// <summary>Field number for the "server_info" field.</summary>
  public const int ServerInfoFieldNumber = 5;
  private string serverInfo_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ServerInfo {
    get { return serverInfo_; }
    set {
      serverInfo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as LcmResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(LcmResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (LogId != other.LogId) return false;
    if (ErrorCode != other.ErrorCode) return false;
    if (ErrorMsg != other.ErrorMsg) return false;
    if (NextIntervalMs != other.NextIntervalMs) return false;
    if (ServerInfo != other.ServerInfo) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (LogId != 0L) hash ^= LogId.GetHashCode();
    if (ErrorCode != 0) hash ^= ErrorCode.GetHashCode();
    if (ErrorMsg.Length != 0) hash ^= ErrorMsg.GetHashCode();
    if (NextIntervalMs != 0L) hash ^= NextIntervalMs.GetHashCode();
    if (ServerInfo.Length != 0) hash ^= ServerInfo.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (LogId != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(LogId);
    }
    if (ErrorCode != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(ErrorCode);
    }
    if (ErrorMsg.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(ErrorMsg);
    }
    if (NextIntervalMs != 0L) {
      output.WriteRawTag(32);
      output.WriteInt64(NextIntervalMs);
    }
    if (ServerInfo.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(ServerInfo);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (LogId != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(LogId);
    }
    if (ErrorCode != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(ErrorCode);
    }
    if (ErrorMsg.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(ErrorMsg);
    }
    if (NextIntervalMs != 0L) {
      output.WriteRawTag(32);
      output.WriteInt64(NextIntervalMs);
    }
    if (ServerInfo.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(ServerInfo);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (LogId != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(LogId);
    }
    if (ErrorCode != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ErrorCode);
    }
    if (ErrorMsg.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ErrorMsg);
    }
    if (NextIntervalMs != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(NextIntervalMs);
    }
    if (ServerInfo.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ServerInfo);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(LcmResponse other) {
    if (other == null) {
      return;
    }
    if (other.LogId != 0L) {
      LogId = other.LogId;
    }
    if (other.ErrorCode != 0) {
      ErrorCode = other.ErrorCode;
    }
    if (other.ErrorMsg.Length != 0) {
      ErrorMsg = other.ErrorMsg;
    }
    if (other.NextIntervalMs != 0L) {
      NextIntervalMs = other.NextIntervalMs;
    }
    if (other.ServerInfo.Length != 0) {
      ServerInfo = other.ServerInfo;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          LogId = input.ReadInt64();
          break;
        }
        case 16: {
          ErrorCode = input.ReadInt32();
          break;
        }
        case 26: {
          ErrorMsg = input.ReadString();
          break;
        }
        case 32: {
          NextIntervalMs = input.ReadInt64();
          break;
        }
        case 42: {
          ServerInfo = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          LogId = input.ReadInt64();
          break;
        }
        case 16: {
          ErrorCode = input.ReadInt32();
          break;
        }
        case 26: {
          ErrorMsg = input.ReadString();
          break;
        }
        case 32: {
          NextIntervalMs = input.ReadInt64();
          break;
        }
        case 42: {
          ServerInfo = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.SerializableAttribute]
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class RpcData : pb::IMessage<RpcData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<RpcData> _parser = new pb::MessageParser<RpcData>(() => new RpcData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<RpcData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::LcmReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RpcData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RpcData(RpcData other) : this() {
    lcmRequest_ = other.lcmRequest_ != null ? other.lcmRequest_.Clone() : null;
    lcmResponse_ = other.lcmResponse_ != null ? other.lcmResponse_.Clone() : null;
    lcmNotify_ = other.lcmNotify_ != null ? other.lcmNotify_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RpcData Clone() {
    return new RpcData(this);
  }

  /// <summary>Field number for the "lcm_request" field.</summary>
  public const int LcmRequestFieldNumber = 1;
  private global::LcmRequest lcmRequest_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::LcmRequest LcmRequest {
    get { return lcmRequest_; }
    set {
      lcmRequest_ = value;
    }
  }

  /// <summary>Field number for the "lcm_response" field.</summary>
  public const int LcmResponseFieldNumber = 2;
  private global::LcmResponse lcmResponse_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::LcmResponse LcmResponse {
    get { return lcmResponse_; }
    set {
      lcmResponse_ = value;
    }
  }

  /// <summary>Field number for the "lcm_notify" field.</summary>
  public const int LcmNotifyFieldNumber = 3;
  private global::LcmNotify lcmNotify_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::LcmNotify LcmNotify {
    get { return lcmNotify_; }
    set {
      lcmNotify_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as RpcData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(RpcData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(LcmRequest, other.LcmRequest)) return false;
    if (!object.Equals(LcmResponse, other.LcmResponse)) return false;
    if (!object.Equals(LcmNotify, other.LcmNotify)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (lcmRequest_ != null) hash ^= LcmRequest.GetHashCode();
    if (lcmResponse_ != null) hash ^= LcmResponse.GetHashCode();
    if (lcmNotify_ != null) hash ^= LcmNotify.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (lcmRequest_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(LcmRequest);
    }
    if (lcmResponse_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(LcmResponse);
    }
    if (lcmNotify_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(LcmNotify);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (lcmRequest_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(LcmRequest);
    }
    if (lcmResponse_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(LcmResponse);
    }
    if (lcmNotify_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(LcmNotify);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (lcmRequest_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(LcmRequest);
    }
    if (lcmResponse_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(LcmResponse);
    }
    if (lcmNotify_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(LcmNotify);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(RpcData other) {
    if (other == null) {
      return;
    }
    if (other.lcmRequest_ != null) {
      if (lcmRequest_ == null) {
        LcmRequest = new global::LcmRequest();
      }
      LcmRequest.MergeFrom(other.LcmRequest);
    }
    if (other.lcmResponse_ != null) {
      if (lcmResponse_ == null) {
        LcmResponse = new global::LcmResponse();
      }
      LcmResponse.MergeFrom(other.LcmResponse);
    }
    if (other.lcmNotify_ != null) {
      if (lcmNotify_ == null) {
        LcmNotify = new global::LcmNotify();
      }
      LcmNotify.MergeFrom(other.LcmNotify);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (lcmRequest_ == null) {
            LcmRequest = new global::LcmRequest();
          }
          input.ReadMessage(LcmRequest);
          break;
        }
        case 18: {
          if (lcmResponse_ == null) {
            LcmResponse = new global::LcmResponse();
          }
          input.ReadMessage(LcmResponse);
          break;
        }
        case 26: {
          if (lcmNotify_ == null) {
            LcmNotify = new global::LcmNotify();
          }
          input.ReadMessage(LcmNotify);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (lcmRequest_ == null) {
            LcmRequest = new global::LcmRequest();
          }
          input.ReadMessage(LcmRequest);
          break;
        }
        case 18: {
          if (lcmResponse_ == null) {
            LcmResponse = new global::LcmResponse();
          }
          input.ReadMessage(LcmResponse);
          break;
        }
        case 26: {
          if (lcmNotify_ == null) {
            LcmNotify = new global::LcmNotify();
          }
          input.ReadMessage(LcmNotify);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
