// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Rpc.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Rpc.proto</summary>
public static partial class RpcReflection {

  #region Descriptor
  /// <summary>File descriptor for Rpc.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static RpcReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CglScGMucHJvdG8iMAoJQ2h1bmtJbmZvEhEKCXN0cmVhbV9pZBgBIAEoAxIQ",
          "CghjaHVua19pZBgCIAEoAyI1Cg5FdmVudFRpbWVzdGFtcBINCgVldmVudBgB",
          "IAEoCRIUCgx0aW1lc3RhbXBfbXMYAiABKAMiawoNUnBjTm90aWZ5TWV0YRIS",
          "CgpzZXJ2aWNlX2lkGAEgASgDEhEKCW1ldGhvZF9pZBgCIAEoAxIOCgZsb2df",
          "aWQYAyABKAMSIwoKZXZlbnRfbGlzdBgEIAMoCzIPLkV2ZW50VGltZXN0YW1w",
          "IoEBCg5ScGNSZXF1ZXN0TWV0YRISCgpzZXJ2aWNlX2lkGAEgASgDEhEKCW1l",
          "dGhvZF9pZBgCIAEoAxIOCgZsb2dfaWQYAyABKAMSEwoLbmVlZF9jb21tb24Y",
          "BCABKAUSIwoKZXZlbnRfbGlzdBgFIAMoCzIPLkV2ZW50VGltZXN0YW1wIpUB",
          "Cg9ScGNSZXNwb25zZU1ldGESEgoKc2VydmljZV9pZBgBIAEoAxIRCgltZXRo",
          "b2RfaWQYAiABKAMSDgoGbG9nX2lkGAMgASgDEhIKCmVycm9yX2NvZGUYBCAB",
          "KAUSEgoKZXJyb3JfdGV4dBgFIAEoCRIjCgpldmVudF9saXN0GAYgAygLMg8u",
          "RXZlbnRUaW1lc3RhbXAiqQIKB1JwY01ldGESIAoHcmVxdWVzdBgBIAEoCzIP",
          "LlJwY1JlcXVlc3RNZXRhEiIKCHJlc3BvbnNlGAIgASgLMhAuUnBjUmVzcG9u",
          "c2VNZXRhEhoKDWNvbXByZXNzX3R5cGUYAyABKAVIAIgBARIWCg5jb3JyZWxh",
          "dGlvbl9pZBgEIAEoAxIXCg9hdHRhY2htZW50X3NpemUYBSABKAUSHgoKY2h1",
          "bmtfaW5mbxgGIAEoCzIKLkNodW5rSW5mbxIbChNhdXRoZW50aWNhdGlvbl9k",
          "YXRhGAcgASgMEh4KBm5vdGlmeRgIIAEoCzIOLlJwY05vdGlmeU1ldGESHAoU",
          "YWNjZXB0X2NvbXByZXNzX3R5cGUYCSABKAVCEAoOX2NvbXByZXNzX3R5cGVC",
          "AkgDYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ChunkInfo), global::ChunkInfo.Parser, new[]{ "StreamId", "ChunkId" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::EventTimestamp), global::EventTimestamp.Parser, new[]{ "Event", "TimestampMs" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::RpcNotifyMeta), global::RpcNotifyMeta.Parser, new[]{ "ServiceId", "MethodId", "LogId", "EventList" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::RpcRequestMeta), global::RpcRequestMeta.Parser, new[]{ "ServiceId", "MethodId", "LogId", "NeedCommon", "EventList" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::RpcResponseMeta), global::RpcResponseMeta.Parser, new[]{ "ServiceId", "MethodId", "LogId", "ErrorCode", "ErrorText", "EventList" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::RpcMeta), global::RpcMeta.Parser, new[]{ "Request", "Response", "CompressType", "CorrelationId", "AttachmentSize", "ChunkInfo", "AuthenticationData", "Notify", "AcceptCompressType" }, new[]{ "CompressType" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.SerializableAttribute]
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ChunkInfo : pb::IMessage<ChunkInfo>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ChunkInfo> _parser = new pb::MessageParser<ChunkInfo>(() => new ChunkInfo());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ChunkInfo> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RpcReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ChunkInfo() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ChunkInfo(ChunkInfo other) : this() {
    streamId_ = other.streamId_;
    chunkId_ = other.chunkId_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ChunkInfo Clone() {
    return new ChunkInfo(this);
  }

  /// <summary>Field number for the "stream_id" field.</summary>
  public const int StreamIdFieldNumber = 1;
  private long streamId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long StreamId {
    get { return streamId_; }
    set {
      streamId_ = value;
    }
  }

  /// <summary>Field number for the "chunk_id" field.</summary>
  public const int ChunkIdFieldNumber = 2;
  private long chunkId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long ChunkId {
    get { return chunkId_; }
    set {
      chunkId_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ChunkInfo);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ChunkInfo other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (StreamId != other.StreamId) return false;
    if (ChunkId != other.ChunkId) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (StreamId != 0L) hash ^= StreamId.GetHashCode();
    if (ChunkId != 0L) hash ^= ChunkId.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (StreamId != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(StreamId);
    }
    if (ChunkId != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(ChunkId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (StreamId != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(StreamId);
    }
    if (ChunkId != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(ChunkId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (StreamId != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(StreamId);
    }
    if (ChunkId != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(ChunkId);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ChunkInfo other) {
    if (other == null) {
      return;
    }
    if (other.StreamId != 0L) {
      StreamId = other.StreamId;
    }
    if (other.ChunkId != 0L) {
      ChunkId = other.ChunkId;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          StreamId = input.ReadInt64();
          break;
        }
        case 16: {
          ChunkId = input.ReadInt64();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          StreamId = input.ReadInt64();
          break;
        }
        case 16: {
          ChunkId = input.ReadInt64();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.SerializableAttribute]
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class EventTimestamp : pb::IMessage<EventTimestamp>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<EventTimestamp> _parser = new pb::MessageParser<EventTimestamp>(() => new EventTimestamp());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<EventTimestamp> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RpcReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EventTimestamp() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EventTimestamp(EventTimestamp other) : this() {
    event_ = other.event_;
    timestampMs_ = other.timestampMs_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EventTimestamp Clone() {
    return new EventTimestamp(this);
  }

  /// <summary>Field number for the "event" field.</summary>
  public const int EventFieldNumber = 1;
  private string event_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Event {
    get { return event_; }
    set {
      event_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "timestamp_ms" field.</summary>
  public const int TimestampMsFieldNumber = 2;
  private long timestampMs_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long TimestampMs {
    get { return timestampMs_; }
    set {
      timestampMs_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as EventTimestamp);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(EventTimestamp other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Event != other.Event) return false;
    if (TimestampMs != other.TimestampMs) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Event.Length != 0) hash ^= Event.GetHashCode();
    if (TimestampMs != 0L) hash ^= TimestampMs.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Event.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Event);
    }
    if (TimestampMs != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(TimestampMs);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Event.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Event);
    }
    if (TimestampMs != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(TimestampMs);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Event.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Event);
    }
    if (TimestampMs != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(TimestampMs);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(EventTimestamp other) {
    if (other == null) {
      return;
    }
    if (other.Event.Length != 0) {
      Event = other.Event;
    }
    if (other.TimestampMs != 0L) {
      TimestampMs = other.TimestampMs;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Event = input.ReadString();
          break;
        }
        case 16: {
          TimestampMs = input.ReadInt64();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Event = input.ReadString();
          break;
        }
        case 16: {
          TimestampMs = input.ReadInt64();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.SerializableAttribute]
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class RpcNotifyMeta : pb::IMessage<RpcNotifyMeta>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<RpcNotifyMeta> _parser = new pb::MessageParser<RpcNotifyMeta>(() => new RpcNotifyMeta());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<RpcNotifyMeta> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RpcReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RpcNotifyMeta() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RpcNotifyMeta(RpcNotifyMeta other) : this() {
    serviceId_ = other.serviceId_;
    methodId_ = other.methodId_;
    logId_ = other.logId_;
    eventList_ = other.eventList_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RpcNotifyMeta Clone() {
    return new RpcNotifyMeta(this);
  }

  /// <summary>Field number for the "service_id" field.</summary>
  public const int ServiceIdFieldNumber = 1;
  private long serviceId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long ServiceId {
    get { return serviceId_; }
    set {
      serviceId_ = value;
    }
  }

  /// <summary>Field number for the "method_id" field.</summary>
  public const int MethodIdFieldNumber = 2;
  private long methodId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long MethodId {
    get { return methodId_; }
    set {
      methodId_ = value;
    }
  }

  /// <summary>Field number for the "log_id" field.</summary>
  public const int LogIdFieldNumber = 3;
  private long logId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long LogId {
    get { return logId_; }
    set {
      logId_ = value;
    }
  }

  /// <summary>Field number for the "event_list" field.</summary>
  public const int EventListFieldNumber = 4;
  private static readonly pb::FieldCodec<global::EventTimestamp> _repeated_eventList_codec
      = pb::FieldCodec.ForMessage(34, global::EventTimestamp.Parser);
  private readonly pbc::RepeatedField<global::EventTimestamp> eventList_ = new pbc::RepeatedField<global::EventTimestamp>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::EventTimestamp> EventList {
    get { return eventList_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as RpcNotifyMeta);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(RpcNotifyMeta other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ServiceId != other.ServiceId) return false;
    if (MethodId != other.MethodId) return false;
    if (LogId != other.LogId) return false;
    if(!eventList_.Equals(other.eventList_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (ServiceId != 0L) hash ^= ServiceId.GetHashCode();
    if (MethodId != 0L) hash ^= MethodId.GetHashCode();
    if (LogId != 0L) hash ^= LogId.GetHashCode();
    hash ^= eventList_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (ServiceId != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(ServiceId);
    }
    if (MethodId != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(MethodId);
    }
    if (LogId != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(LogId);
    }
    eventList_.WriteTo(output, _repeated_eventList_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (ServiceId != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(ServiceId);
    }
    if (MethodId != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(MethodId);
    }
    if (LogId != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(LogId);
    }
    eventList_.WriteTo(ref output, _repeated_eventList_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (ServiceId != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(ServiceId);
    }
    if (MethodId != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(MethodId);
    }
    if (LogId != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(LogId);
    }
    size += eventList_.CalculateSize(_repeated_eventList_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(RpcNotifyMeta other) {
    if (other == null) {
      return;
    }
    if (other.ServiceId != 0L) {
      ServiceId = other.ServiceId;
    }
    if (other.MethodId != 0L) {
      MethodId = other.MethodId;
    }
    if (other.LogId != 0L) {
      LogId = other.LogId;
    }
    eventList_.Add(other.eventList_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          ServiceId = input.ReadInt64();
          break;
        }
        case 16: {
          MethodId = input.ReadInt64();
          break;
        }
        case 24: {
          LogId = input.ReadInt64();
          break;
        }
        case 34: {
          eventList_.AddEntriesFrom(input, _repeated_eventList_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          ServiceId = input.ReadInt64();
          break;
        }
        case 16: {
          MethodId = input.ReadInt64();
          break;
        }
        case 24: {
          LogId = input.ReadInt64();
          break;
        }
        case 34: {
          eventList_.AddEntriesFrom(ref input, _repeated_eventList_codec);
          break;
        }
      }
    }
  }
  #endif

}

[global::System.SerializableAttribute]
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class RpcRequestMeta : pb::IMessage<RpcRequestMeta>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<RpcRequestMeta> _parser = new pb::MessageParser<RpcRequestMeta>(() => new RpcRequestMeta());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<RpcRequestMeta> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RpcReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RpcRequestMeta() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RpcRequestMeta(RpcRequestMeta other) : this() {
    serviceId_ = other.serviceId_;
    methodId_ = other.methodId_;
    logId_ = other.logId_;
    needCommon_ = other.needCommon_;
    eventList_ = other.eventList_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RpcRequestMeta Clone() {
    return new RpcRequestMeta(this);
  }

  /// <summary>Field number for the "service_id" field.</summary>
  public const int ServiceIdFieldNumber = 1;
  private long serviceId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long ServiceId {
    get { return serviceId_; }
    set {
      serviceId_ = value;
    }
  }

  /// <summary>Field number for the "method_id" field.</summary>
  public const int MethodIdFieldNumber = 2;
  private long methodId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long MethodId {
    get { return methodId_; }
    set {
      methodId_ = value;
    }
  }

  /// <summary>Field number for the "log_id" field.</summary>
  public const int LogIdFieldNumber = 3;
  private long logId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long LogId {
    get { return logId_; }
    set {
      logId_ = value;
    }
  }

  /// <summary>Field number for the "need_common" field.</summary>
  public const int NeedCommonFieldNumber = 4;
  private int needCommon_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int NeedCommon {
    get { return needCommon_; }
    set {
      needCommon_ = value;
    }
  }

  /// <summary>Field number for the "event_list" field.</summary>
  public const int EventListFieldNumber = 5;
  private static readonly pb::FieldCodec<global::EventTimestamp> _repeated_eventList_codec
      = pb::FieldCodec.ForMessage(42, global::EventTimestamp.Parser);
  private readonly pbc::RepeatedField<global::EventTimestamp> eventList_ = new pbc::RepeatedField<global::EventTimestamp>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::EventTimestamp> EventList {
    get { return eventList_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as RpcRequestMeta);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(RpcRequestMeta other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ServiceId != other.ServiceId) return false;
    if (MethodId != other.MethodId) return false;
    if (LogId != other.LogId) return false;
    if (NeedCommon != other.NeedCommon) return false;
    if(!eventList_.Equals(other.eventList_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (ServiceId != 0L) hash ^= ServiceId.GetHashCode();
    if (MethodId != 0L) hash ^= MethodId.GetHashCode();
    if (LogId != 0L) hash ^= LogId.GetHashCode();
    if (NeedCommon != 0) hash ^= NeedCommon.GetHashCode();
    hash ^= eventList_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (ServiceId != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(ServiceId);
    }
    if (MethodId != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(MethodId);
    }
    if (LogId != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(LogId);
    }
    if (NeedCommon != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(NeedCommon);
    }
    eventList_.WriteTo(output, _repeated_eventList_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (ServiceId != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(ServiceId);
    }
    if (MethodId != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(MethodId);
    }
    if (LogId != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(LogId);
    }
    if (NeedCommon != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(NeedCommon);
    }
    eventList_.WriteTo(ref output, _repeated_eventList_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (ServiceId != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(ServiceId);
    }
    if (MethodId != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(MethodId);
    }
    if (LogId != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(LogId);
    }
    if (NeedCommon != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(NeedCommon);
    }
    size += eventList_.CalculateSize(_repeated_eventList_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(RpcRequestMeta other) {
    if (other == null) {
      return;
    }
    if (other.ServiceId != 0L) {
      ServiceId = other.ServiceId;
    }
    if (other.MethodId != 0L) {
      MethodId = other.MethodId;
    }
    if (other.LogId != 0L) {
      LogId = other.LogId;
    }
    if (other.NeedCommon != 0) {
      NeedCommon = other.NeedCommon;
    }
    eventList_.Add(other.eventList_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          ServiceId = input.ReadInt64();
          break;
        }
        case 16: {
          MethodId = input.ReadInt64();
          break;
        }
        case 24: {
          LogId = input.ReadInt64();
          break;
        }
        case 32: {
          NeedCommon = input.ReadInt32();
          break;
        }
        case 42: {
          eventList_.AddEntriesFrom(input, _repeated_eventList_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          ServiceId = input.ReadInt64();
          break;
        }
        case 16: {
          MethodId = input.ReadInt64();
          break;
        }
        case 24: {
          LogId = input.ReadInt64();
          break;
        }
        case 32: {
          NeedCommon = input.ReadInt32();
          break;
        }
        case 42: {
          eventList_.AddEntriesFrom(ref input, _repeated_eventList_codec);
          break;
        }
      }
    }
  }
  #endif

}

[global::System.SerializableAttribute]
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class RpcResponseMeta : pb::IMessage<RpcResponseMeta>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<RpcResponseMeta> _parser = new pb::MessageParser<RpcResponseMeta>(() => new RpcResponseMeta());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<RpcResponseMeta> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RpcReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RpcResponseMeta() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RpcResponseMeta(RpcResponseMeta other) : this() {
    serviceId_ = other.serviceId_;
    methodId_ = other.methodId_;
    logId_ = other.logId_;
    errorCode_ = other.errorCode_;
    errorText_ = other.errorText_;
    eventList_ = other.eventList_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RpcResponseMeta Clone() {
    return new RpcResponseMeta(this);
  }

  /// <summary>Field number for the "service_id" field.</summary>
  public const int ServiceIdFieldNumber = 1;
  private long serviceId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long ServiceId {
    get { return serviceId_; }
    set {
      serviceId_ = value;
    }
  }

  /// <summary>Field number for the "method_id" field.</summary>
  public const int MethodIdFieldNumber = 2;
  private long methodId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long MethodId {
    get { return methodId_; }
    set {
      methodId_ = value;
    }
  }

  /// <summary>Field number for the "log_id" field.</summary>
  public const int LogIdFieldNumber = 3;
  private long logId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long LogId {
    get { return logId_; }
    set {
      logId_ = value;
    }
  }

  /// <summary>Field number for the "error_code" field.</summary>
  public const int ErrorCodeFieldNumber = 4;
  private int errorCode_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ErrorCode {
    get { return errorCode_; }
    set {
      errorCode_ = value;
    }
  }

  /// <summary>Field number for the "error_text" field.</summary>
  public const int ErrorTextFieldNumber = 5;
  private string errorText_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ErrorText {
    get { return errorText_; }
    set {
      errorText_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "event_list" field.</summary>
  public const int EventListFieldNumber = 6;
  private static readonly pb::FieldCodec<global::EventTimestamp> _repeated_eventList_codec
      = pb::FieldCodec.ForMessage(50, global::EventTimestamp.Parser);
  private readonly pbc::RepeatedField<global::EventTimestamp> eventList_ = new pbc::RepeatedField<global::EventTimestamp>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::EventTimestamp> EventList {
    get { return eventList_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as RpcResponseMeta);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(RpcResponseMeta other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ServiceId != other.ServiceId) return false;
    if (MethodId != other.MethodId) return false;
    if (LogId != other.LogId) return false;
    if (ErrorCode != other.ErrorCode) return false;
    if (ErrorText != other.ErrorText) return false;
    if(!eventList_.Equals(other.eventList_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (ServiceId != 0L) hash ^= ServiceId.GetHashCode();
    if (MethodId != 0L) hash ^= MethodId.GetHashCode();
    if (LogId != 0L) hash ^= LogId.GetHashCode();
    if (ErrorCode != 0) hash ^= ErrorCode.GetHashCode();
    if (ErrorText.Length != 0) hash ^= ErrorText.GetHashCode();
    hash ^= eventList_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (ServiceId != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(ServiceId);
    }
    if (MethodId != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(MethodId);
    }
    if (LogId != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(LogId);
    }
    if (ErrorCode != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(ErrorCode);
    }
    if (ErrorText.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(ErrorText);
    }
    eventList_.WriteTo(output, _repeated_eventList_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (ServiceId != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(ServiceId);
    }
    if (MethodId != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(MethodId);
    }
    if (LogId != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(LogId);
    }
    if (ErrorCode != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(ErrorCode);
    }
    if (ErrorText.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(ErrorText);
    }
    eventList_.WriteTo(ref output, _repeated_eventList_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (ServiceId != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(ServiceId);
    }
    if (MethodId != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(MethodId);
    }
    if (LogId != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(LogId);
    }
    if (ErrorCode != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ErrorCode);
    }
    if (ErrorText.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ErrorText);
    }
    size += eventList_.CalculateSize(_repeated_eventList_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(RpcResponseMeta other) {
    if (other == null) {
      return;
    }
    if (other.ServiceId != 0L) {
      ServiceId = other.ServiceId;
    }
    if (other.MethodId != 0L) {
      MethodId = other.MethodId;
    }
    if (other.LogId != 0L) {
      LogId = other.LogId;
    }
    if (other.ErrorCode != 0) {
      ErrorCode = other.ErrorCode;
    }
    if (other.ErrorText.Length != 0) {
      ErrorText = other.ErrorText;
    }
    eventList_.Add(other.eventList_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          ServiceId = input.ReadInt64();
          break;
        }
        case 16: {
          MethodId = input.ReadInt64();
          break;
        }
        case 24: {
          LogId = input.ReadInt64();
          break;
        }
        case 32: {
          ErrorCode = input.ReadInt32();
          break;
        }
        case 42: {
          ErrorText = input.ReadString();
          break;
        }
        case 50: {
          eventList_.AddEntriesFrom(input, _repeated_eventList_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          ServiceId = input.ReadInt64();
          break;
        }
        case 16: {
          MethodId = input.ReadInt64();
          break;
        }
        case 24: {
          LogId = input.ReadInt64();
          break;
        }
        case 32: {
          ErrorCode = input.ReadInt32();
          break;
        }
        case 42: {
          ErrorText = input.ReadString();
          break;
        }
        case 50: {
          eventList_.AddEntriesFrom(ref input, _repeated_eventList_codec);
          break;
        }
      }
    }
  }
  #endif

}

[global::System.SerializableAttribute]
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class RpcMeta : pb::IMessage<RpcMeta>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<RpcMeta> _parser = new pb::MessageParser<RpcMeta>(() => new RpcMeta());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<RpcMeta> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RpcReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RpcMeta() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RpcMeta(RpcMeta other) : this() {
    _hasBits0 = other._hasBits0;
    request_ = other.request_ != null ? other.request_.Clone() : null;
    response_ = other.response_ != null ? other.response_.Clone() : null;
    compressType_ = other.compressType_;
    correlationId_ = other.correlationId_;
    attachmentSize_ = other.attachmentSize_;
    chunkInfo_ = other.chunkInfo_ != null ? other.chunkInfo_.Clone() : null;
    authenticationData_ = other.authenticationData_;
    notify_ = other.notify_ != null ? other.notify_.Clone() : null;
    acceptCompressType_ = other.acceptCompressType_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RpcMeta Clone() {
    return new RpcMeta(this);
  }

  /// <summary>Field number for the "request" field.</summary>
  public const int RequestFieldNumber = 1;
  private global::RpcRequestMeta request_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::RpcRequestMeta Request {
    get { return request_; }
    set {
      request_ = value;
    }
  }

  /// <summary>Field number for the "response" field.</summary>
  public const int ResponseFieldNumber = 2;
  private global::RpcResponseMeta response_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::RpcResponseMeta Response {
    get { return response_; }
    set {
      response_ = value;
    }
  }

  /// <summary>Field number for the "compress_type" field.</summary>
  public const int CompressTypeFieldNumber = 3;
  private readonly static int CompressTypeDefaultValue = 0;

  private int compressType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CompressType {
    get { if ((_hasBits0 & 1) != 0) { return compressType_; } else { return CompressTypeDefaultValue; } }
    set {
      _hasBits0 |= 1;
      compressType_ = value;
    }
  }
  /// <summary>Gets whether the "compress_type" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasCompressType {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "compress_type" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearCompressType() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "correlation_id" field.</summary>
  public const int CorrelationIdFieldNumber = 4;
  private long correlationId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long CorrelationId {
    get { return correlationId_; }
    set {
      correlationId_ = value;
    }
  }

  /// <summary>Field number for the "attachment_size" field.</summary>
  public const int AttachmentSizeFieldNumber = 5;
  private int attachmentSize_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int AttachmentSize {
    get { return attachmentSize_; }
    set {
      attachmentSize_ = value;
    }
  }

  /// <summary>Field number for the "chunk_info" field.</summary>
  public const int ChunkInfoFieldNumber = 6;
  private global::ChunkInfo chunkInfo_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ChunkInfo ChunkInfo {
    get { return chunkInfo_; }
    set {
      chunkInfo_ = value;
    }
  }

  /// <summary>Field number for the "authentication_data" field.</summary>
  public const int AuthenticationDataFieldNumber = 7;
  private pb::ByteString authenticationData_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString AuthenticationData {
    get { return authenticationData_; }
    set {
      authenticationData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "notify" field.</summary>
  public const int NotifyFieldNumber = 8;
  private global::RpcNotifyMeta notify_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::RpcNotifyMeta Notify {
    get { return notify_; }
    set {
      notify_ = value;
    }
  }

  /// <summary>Field number for the "accept_compress_type" field.</summary>
  public const int AcceptCompressTypeFieldNumber = 9;
  private int acceptCompressType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int AcceptCompressType {
    get { return acceptCompressType_; }
    set {
      acceptCompressType_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as RpcMeta);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(RpcMeta other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Request, other.Request)) return false;
    if (!object.Equals(Response, other.Response)) return false;
    if (CompressType != other.CompressType) return false;
    if (CorrelationId != other.CorrelationId) return false;
    if (AttachmentSize != other.AttachmentSize) return false;
    if (!object.Equals(ChunkInfo, other.ChunkInfo)) return false;
    if (AuthenticationData != other.AuthenticationData) return false;
    if (!object.Equals(Notify, other.Notify)) return false;
    if (AcceptCompressType != other.AcceptCompressType) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (request_ != null) hash ^= Request.GetHashCode();
    if (response_ != null) hash ^= Response.GetHashCode();
    if (HasCompressType) hash ^= CompressType.GetHashCode();
    if (CorrelationId != 0L) hash ^= CorrelationId.GetHashCode();
    if (AttachmentSize != 0) hash ^= AttachmentSize.GetHashCode();
    if (chunkInfo_ != null) hash ^= ChunkInfo.GetHashCode();
    if (AuthenticationData.Length != 0) hash ^= AuthenticationData.GetHashCode();
    if (notify_ != null) hash ^= Notify.GetHashCode();
    if (AcceptCompressType != 0) hash ^= AcceptCompressType.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (request_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Request);
    }
    if (response_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Response);
    }
    if (HasCompressType) {
      output.WriteRawTag(24);
      output.WriteInt32(CompressType);
    }
    if (CorrelationId != 0L) {
      output.WriteRawTag(32);
      output.WriteInt64(CorrelationId);
    }
    if (AttachmentSize != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(AttachmentSize);
    }
    if (chunkInfo_ != null) {
      output.WriteRawTag(50);
      output.WriteMessage(ChunkInfo);
    }
    if (AuthenticationData.Length != 0) {
      output.WriteRawTag(58);
      output.WriteBytes(AuthenticationData);
    }
    if (notify_ != null) {
      output.WriteRawTag(66);
      output.WriteMessage(Notify);
    }
    if (AcceptCompressType != 0) {
      output.WriteRawTag(72);
      output.WriteInt32(AcceptCompressType);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (request_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Request);
    }
    if (response_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Response);
    }
    if (HasCompressType) {
      output.WriteRawTag(24);
      output.WriteInt32(CompressType);
    }
    if (CorrelationId != 0L) {
      output.WriteRawTag(32);
      output.WriteInt64(CorrelationId);
    }
    if (AttachmentSize != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(AttachmentSize);
    }
    if (chunkInfo_ != null) {
      output.WriteRawTag(50);
      output.WriteMessage(ChunkInfo);
    }
    if (AuthenticationData.Length != 0) {
      output.WriteRawTag(58);
      output.WriteBytes(AuthenticationData);
    }
    if (notify_ != null) {
      output.WriteRawTag(66);
      output.WriteMessage(Notify);
    }
    if (AcceptCompressType != 0) {
      output.WriteRawTag(72);
      output.WriteInt32(AcceptCompressType);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (request_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Request);
    }
    if (response_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Response);
    }
    if (HasCompressType) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(CompressType);
    }
    if (CorrelationId != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(CorrelationId);
    }
    if (AttachmentSize != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(AttachmentSize);
    }
    if (chunkInfo_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChunkInfo);
    }
    if (AuthenticationData.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(AuthenticationData);
    }
    if (notify_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Notify);
    }
    if (AcceptCompressType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(AcceptCompressType);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(RpcMeta other) {
    if (other == null) {
      return;
    }
    if (other.request_ != null) {
      if (request_ == null) {
        Request = new global::RpcRequestMeta();
      }
      Request.MergeFrom(other.Request);
    }
    if (other.response_ != null) {
      if (response_ == null) {
        Response = new global::RpcResponseMeta();
      }
      Response.MergeFrom(other.Response);
    }
    if (other.HasCompressType) {
      CompressType = other.CompressType;
    }
    if (other.CorrelationId != 0L) {
      CorrelationId = other.CorrelationId;
    }
    if (other.AttachmentSize != 0) {
      AttachmentSize = other.AttachmentSize;
    }
    if (other.chunkInfo_ != null) {
      if (chunkInfo_ == null) {
        ChunkInfo = new global::ChunkInfo();
      }
      ChunkInfo.MergeFrom(other.ChunkInfo);
    }
    if (other.AuthenticationData.Length != 0) {
      AuthenticationData = other.AuthenticationData;
    }
    if (other.notify_ != null) {
      if (notify_ == null) {
        Notify = new global::RpcNotifyMeta();
      }
      Notify.MergeFrom(other.Notify);
    }
    if (other.AcceptCompressType != 0) {
      AcceptCompressType = other.AcceptCompressType;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (request_ == null) {
            Request = new global::RpcRequestMeta();
          }
          input.ReadMessage(Request);
          break;
        }
        case 18: {
          if (response_ == null) {
            Response = new global::RpcResponseMeta();
          }
          input.ReadMessage(Response);
          break;
        }
        case 24: {
          CompressType = input.ReadInt32();
          break;
        }
        case 32: {
          CorrelationId = input.ReadInt64();
          break;
        }
        case 40: {
          AttachmentSize = input.ReadInt32();
          break;
        }
        case 50: {
          if (chunkInfo_ == null) {
            ChunkInfo = new global::ChunkInfo();
          }
          input.ReadMessage(ChunkInfo);
          break;
        }
        case 58: {
          AuthenticationData = input.ReadBytes();
          break;
        }
        case 66: {
          if (notify_ == null) {
            Notify = new global::RpcNotifyMeta();
          }
          input.ReadMessage(Notify);
          break;
        }
        case 72: {
          AcceptCompressType = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (request_ == null) {
            Request = new global::RpcRequestMeta();
          }
          input.ReadMessage(Request);
          break;
        }
        case 18: {
          if (response_ == null) {
            Response = new global::RpcResponseMeta();
          }
          input.ReadMessage(Response);
          break;
        }
        case 24: {
          CompressType = input.ReadInt32();
          break;
        }
        case 32: {
          CorrelationId = input.ReadInt64();
          break;
        }
        case 40: {
          AttachmentSize = input.ReadInt32();
          break;
        }
        case 50: {
          if (chunkInfo_ == null) {
            ChunkInfo = new global::ChunkInfo();
          }
          input.ReadMessage(ChunkInfo);
          break;
        }
        case 58: {
          AuthenticationData = input.ReadBytes();
          break;
        }
        case 66: {
          if (notify_ == null) {
            Notify = new global::RpcNotifyMeta();
          }
          input.ReadMessage(Notify);
          break;
        }
        case 72: {
          AcceptCompressType = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
