// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SimpleForum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from SimpleForum.proto</summary>
public static partial class SimpleForumReflection {

  #region Descriptor
  /// <summary>File descriptor for SimpleForum.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static SimpleForumReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChFTaW1wbGVGb3J1bS5wcm90byJ4CgtTaW1wbGVGb3J1bRIKCgJpZBgBIAEo",
          "AxIMCgRuYW1lGAIgASgJEhMKC2ZpcnN0X2NsYXNzGAcgASgJEhQKDHNlY29u",
          "ZF9jbGFzcxgIIAEoCRISCgptZW1iZXJfbnVtGAwgASgFEhAKCHBvc3RfbnVt",
          "GA0gASgFYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::SimpleForum), global::SimpleForum.Parser, new[]{ "Id", "Name", "FirstClass", "SecondClass", "MemberNum", "PostNum" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.SerializableAttribute]
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class SimpleForum : pb::IMessage<SimpleForum>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<SimpleForum> _parser = new pb::MessageParser<SimpleForum>(() => new SimpleForum());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<SimpleForum> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SimpleForumReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SimpleForum() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SimpleForum(SimpleForum other) : this() {
    id_ = other.id_;
    name_ = other.name_;
    firstClass_ = other.firstClass_;
    secondClass_ = other.secondClass_;
    memberNum_ = other.memberNum_;
    postNum_ = other.postNum_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SimpleForum Clone() {
    return new SimpleForum(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private long id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 2;
  private string name_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "first_class" field.</summary>
  public const int FirstClassFieldNumber = 7;
  private string firstClass_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string FirstClass {
    get { return firstClass_; }
    set {
      firstClass_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "second_class" field.</summary>
  public const int SecondClassFieldNumber = 8;
  private string secondClass_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string SecondClass {
    get { return secondClass_; }
    set {
      secondClass_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "member_num" field.</summary>
  public const int MemberNumFieldNumber = 12;
  private int memberNum_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int MemberNum {
    get { return memberNum_; }
    set {
      memberNum_ = value;
    }
  }

  /// <summary>Field number for the "post_num" field.</summary>
  public const int PostNumFieldNumber = 13;
  private int postNum_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int PostNum {
    get { return postNum_; }
    set {
      postNum_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as SimpleForum);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(SimpleForum other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Name != other.Name) return false;
    if (FirstClass != other.FirstClass) return false;
    if (SecondClass != other.SecondClass) return false;
    if (MemberNum != other.MemberNum) return false;
    if (PostNum != other.PostNum) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0L) hash ^= Id.GetHashCode();
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (FirstClass.Length != 0) hash ^= FirstClass.GetHashCode();
    if (SecondClass.Length != 0) hash ^= SecondClass.GetHashCode();
    if (MemberNum != 0) hash ^= MemberNum.GetHashCode();
    if (PostNum != 0) hash ^= PostNum.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Id);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Name);
    }
    if (FirstClass.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(FirstClass);
    }
    if (SecondClass.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(SecondClass);
    }
    if (MemberNum != 0) {
      output.WriteRawTag(96);
      output.WriteInt32(MemberNum);
    }
    if (PostNum != 0) {
      output.WriteRawTag(104);
      output.WriteInt32(PostNum);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Id);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Name);
    }
    if (FirstClass.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(FirstClass);
    }
    if (SecondClass.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(SecondClass);
    }
    if (MemberNum != 0) {
      output.WriteRawTag(96);
      output.WriteInt32(MemberNum);
    }
    if (PostNum != 0) {
      output.WriteRawTag(104);
      output.WriteInt32(PostNum);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
    }
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (FirstClass.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(FirstClass);
    }
    if (SecondClass.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(SecondClass);
    }
    if (MemberNum != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(MemberNum);
    }
    if (PostNum != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PostNum);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(SimpleForum other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0L) {
      Id = other.Id;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.FirstClass.Length != 0) {
      FirstClass = other.FirstClass;
    }
    if (other.SecondClass.Length != 0) {
      SecondClass = other.SecondClass;
    }
    if (other.MemberNum != 0) {
      MemberNum = other.MemberNum;
    }
    if (other.PostNum != 0) {
      PostNum = other.PostNum;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadInt64();
          break;
        }
        case 18: {
          Name = input.ReadString();
          break;
        }
        case 58: {
          FirstClass = input.ReadString();
          break;
        }
        case 66: {
          SecondClass = input.ReadString();
          break;
        }
        case 96: {
          MemberNum = input.ReadInt32();
          break;
        }
        case 104: {
          PostNum = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = input.ReadInt64();
          break;
        }
        case 18: {
          Name = input.ReadString();
          break;
        }
        case 58: {
          FirstClass = input.ReadString();
          break;
        }
        case 66: {
          SecondClass = input.ReadString();
          break;
        }
        case 96: {
          MemberNum = input.ReadInt32();
          break;
        }
        case 104: {
          PostNum = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
