// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: UserMuteQueryResIdl.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from UserMuteQueryResIdl.proto</summary>
internal static partial class UserMuteQueryResIdlReflection {

  #region Descriptor
  /// <summary>File descriptor for UserMuteQueryResIdl.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static UserMuteQueryResIdlReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChlVc2VyTXV0ZVF1ZXJ5UmVzSWRsLnByb3RvGgtFcnJvci5wcm90bxoKUGFn",
          "ZS5wcm90byKbAgoTVXNlck11dGVRdWVyeVJlc0lkbBIqCgRkYXRhGAEgASgL",
          "MhwuVXNlck11dGVRdWVyeVJlc0lkbC5EYXRhUmVzEhUKBWVycm9yGAIgASgL",
          "MgYuRXJyb3IawAEKB0RhdGFSZXMSOAoJbXV0ZV91c2VyGAEgAygLMiUuVXNl",
          "ck11dGVRdWVyeVJlc0lkbC5EYXRhUmVzLk11dGVVc2VyEhMKBHBhZ2UYAiAB",
          "KAsyBS5QYWdlGmYKCE11dGVVc2VyEg8KB3VzZXJfaWQYASABKAMSEQoJdXNl",
          "cl9uYW1lGAIgASgJEhEKCW11dGVfdGltZRgDIAEoBRIQCghwb3J0cmFpdBgE",
          "IAEoCRIRCgluYW1lX3Nob3cYBSABKAliBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::ErrorReflection.Descriptor, global::PageReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::UserMuteQueryResIdl), global::UserMuteQueryResIdl.Parser, new[]{ "Data", "Error" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::UserMuteQueryResIdl.Types.DataRes), global::UserMuteQueryResIdl.Types.DataRes.Parser, new[]{ "MuteUser", "Page" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::UserMuteQueryResIdl.Types.DataRes.Types.MuteUser), global::UserMuteQueryResIdl.Types.DataRes.Types.MuteUser.Parser, new[]{ "UserId", "UserName", "MuteTime", "Portrait", "NameShow" }, null, null, null, null)})})
        }));
  }
  #endregion

}
#region Messages
[global::System.SerializableAttribute]
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
internal sealed partial class UserMuteQueryResIdl : pb::IMessage<UserMuteQueryResIdl>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<UserMuteQueryResIdl> _parser = new pb::MessageParser<UserMuteQueryResIdl>(() => new UserMuteQueryResIdl());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<UserMuteQueryResIdl> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::UserMuteQueryResIdlReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UserMuteQueryResIdl() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UserMuteQueryResIdl(UserMuteQueryResIdl other) : this() {
    data_ = other.data_ != null ? other.data_.Clone() : null;
    error_ = other.error_ != null ? other.error_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UserMuteQueryResIdl Clone() {
    return new UserMuteQueryResIdl(this);
  }

  /// <summary>Field number for the "data" field.</summary>
  public const int DataFieldNumber = 1;
  private global::UserMuteQueryResIdl.Types.DataRes data_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::UserMuteQueryResIdl.Types.DataRes Data {
    get { return data_; }
    set {
      data_ = value;
    }
  }

  /// <summary>Field number for the "error" field.</summary>
  public const int ErrorFieldNumber = 2;
  private global::Error error_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Error Error {
    get { return error_; }
    set {
      error_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as UserMuteQueryResIdl);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(UserMuteQueryResIdl other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Data, other.Data)) return false;
    if (!object.Equals(Error, other.Error)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (data_ != null) hash ^= Data.GetHashCode();
    if (error_ != null) hash ^= Error.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (data_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Data);
    }
    if (error_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Error);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (data_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Data);
    }
    if (error_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Error);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (data_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
    }
    if (error_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Error);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(UserMuteQueryResIdl other) {
    if (other == null) {
      return;
    }
    if (other.data_ != null) {
      if (data_ == null) {
        Data = new global::UserMuteQueryResIdl.Types.DataRes();
      }
      Data.MergeFrom(other.Data);
    }
    if (other.error_ != null) {
      if (error_ == null) {
        Error = new global::Error();
      }
      Error.MergeFrom(other.Error);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (data_ == null) {
            Data = new global::UserMuteQueryResIdl.Types.DataRes();
          }
          input.ReadMessage(Data);
          break;
        }
        case 18: {
          if (error_ == null) {
            Error = new global::Error();
          }
          input.ReadMessage(Error);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (data_ == null) {
            Data = new global::UserMuteQueryResIdl.Types.DataRes();
          }
          input.ReadMessage(Data);
          break;
        }
        case 18: {
          if (error_ == null) {
            Error = new global::Error();
          }
          input.ReadMessage(Error);
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the UserMuteQueryResIdl message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    [global::System.SerializableAttribute]
    [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
    internal sealed partial class DataRes : pb::IMessage<DataRes>
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
    #endif
    {
      private static readonly pb::MessageParser<DataRes> _parser = new pb::MessageParser<DataRes>(() => new DataRes());
      private pb::UnknownFieldSet _unknownFields;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pb::MessageParser<DataRes> Parser { get { return _parser; } }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pbr::MessageDescriptor Descriptor {
        get { return global::UserMuteQueryResIdl.Descriptor.NestedTypes[0]; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      pbr::MessageDescriptor pb::IMessage.Descriptor {
        get { return Descriptor; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public DataRes() {
        OnConstruction();
      }

      partial void OnConstruction();

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public DataRes(DataRes other) : this() {
        muteUser_ = other.muteUser_.Clone();
        page_ = other.page_ != null ? other.page_.Clone() : null;
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public DataRes Clone() {
        return new DataRes(this);
      }

      /// <summary>Field number for the "mute_user" field.</summary>
      public const int MuteUserFieldNumber = 1;
      private static readonly pb::FieldCodec<global::UserMuteQueryResIdl.Types.DataRes.Types.MuteUser> _repeated_muteUser_codec
          = pb::FieldCodec.ForMessage(10, global::UserMuteQueryResIdl.Types.DataRes.Types.MuteUser.Parser);
      private readonly pbc::RepeatedField<global::UserMuteQueryResIdl.Types.DataRes.Types.MuteUser> muteUser_ = new pbc::RepeatedField<global::UserMuteQueryResIdl.Types.DataRes.Types.MuteUser>();
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public pbc::RepeatedField<global::UserMuteQueryResIdl.Types.DataRes.Types.MuteUser> MuteUser {
        get { return muteUser_; }
      }

      /// <summary>Field number for the "page" field.</summary>
      public const int PageFieldNumber = 2;
      private global::Page page_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public global::Page Page {
        get { return page_; }
        set {
          page_ = value;
        }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override bool Equals(object other) {
        return Equals(other as DataRes);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool Equals(DataRes other) {
        if (ReferenceEquals(other, null)) {
          return false;
        }
        if (ReferenceEquals(other, this)) {
          return true;
        }
        if(!muteUser_.Equals(other.muteUser_)) return false;
        if (!object.Equals(Page, other.Page)) return false;
        return Equals(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override int GetHashCode() {
        int hash = 1;
        hash ^= muteUser_.GetHashCode();
        if (page_ != null) hash ^= Page.GetHashCode();
        if (_unknownFields != null) {
          hash ^= _unknownFields.GetHashCode();
        }
        return hash;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override string ToString() {
        return pb::JsonFormatter.ToDiagnosticString(this);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void WriteTo(pb::CodedOutputStream output) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        output.WriteRawMessage(this);
      #else
        muteUser_.WriteTo(output, _repeated_muteUser_codec);
        if (page_ != null) {
          output.WriteRawTag(18);
          output.WriteMessage(Page);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(output);
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
        muteUser_.WriteTo(ref output, _repeated_muteUser_codec);
        if (page_ != null) {
          output.WriteRawTag(18);
          output.WriteMessage(Page);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(ref output);
        }
      }
      #endif

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public int CalculateSize() {
        int size = 0;
        size += muteUser_.CalculateSize(_repeated_muteUser_codec);
        if (page_ != null) {
          size += 1 + pb::CodedOutputStream.ComputeMessageSize(Page);
        }
        if (_unknownFields != null) {
          size += _unknownFields.CalculateSize();
        }
        return size;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(DataRes other) {
        if (other == null) {
          return;
        }
        muteUser_.Add(other.muteUser_);
        if (other.page_ != null) {
          if (page_ == null) {
            Page = new global::Page();
          }
          Page.MergeFrom(other.Page);
        }
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(pb::CodedInputStream input) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        input.ReadRawMessage(this);
      #else
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
        if ((tag & 7) == 4) {
          // Abort on any end group tag.
          return;
        }
        switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
              break;
            case 10: {
              muteUser_.AddEntriesFrom(input, _repeated_muteUser_codec);
              break;
            }
            case 18: {
              if (page_ == null) {
                Page = new global::Page();
              }
              input.ReadMessage(Page);
              break;
            }
          }
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
        if ((tag & 7) == 4) {
          // Abort on any end group tag.
          return;
        }
        switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
              break;
            case 10: {
              muteUser_.AddEntriesFrom(ref input, _repeated_muteUser_codec);
              break;
            }
            case 18: {
              if (page_ == null) {
                Page = new global::Page();
              }
              input.ReadMessage(Page);
              break;
            }
          }
        }
      }
      #endif

      #region Nested types
      /// <summary>Container for nested types declared in the DataRes message type.</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static partial class Types {
        [global::System.SerializableAttribute]
        [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
        internal sealed partial class MuteUser : pb::IMessage<MuteUser>
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            , pb::IBufferMessage
        #endif
        {
          private static readonly pb::MessageParser<MuteUser> _parser = new pb::MessageParser<MuteUser>(() => new MuteUser());
          private pb::UnknownFieldSet _unknownFields;
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public static pb::MessageParser<MuteUser> Parser { get { return _parser; } }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public static pbr::MessageDescriptor Descriptor {
            get { return global::UserMuteQueryResIdl.Types.DataRes.Descriptor.NestedTypes[0]; }
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          pbr::MessageDescriptor pb::IMessage.Descriptor {
            get { return Descriptor; }
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public MuteUser() {
            OnConstruction();
          }

          partial void OnConstruction();

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public MuteUser(MuteUser other) : this() {
            userId_ = other.userId_;
            userName_ = other.userName_;
            muteTime_ = other.muteTime_;
            portrait_ = other.portrait_;
            nameShow_ = other.nameShow_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public MuteUser Clone() {
            return new MuteUser(this);
          }

          /// <summary>Field number for the "user_id" field.</summary>
          public const int UserIdFieldNumber = 1;
          private long userId_;
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public long UserId {
            get { return userId_; }
            set {
              userId_ = value;
            }
          }

          /// <summary>Field number for the "user_name" field.</summary>
          public const int UserNameFieldNumber = 2;
          private string userName_ = "";
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public string UserName {
            get { return userName_; }
            set {
              userName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
          }

          /// <summary>Field number for the "mute_time" field.</summary>
          public const int MuteTimeFieldNumber = 3;
          private int muteTime_;
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public int MuteTime {
            get { return muteTime_; }
            set {
              muteTime_ = value;
            }
          }

          /// <summary>Field number for the "portrait" field.</summary>
          public const int PortraitFieldNumber = 4;
          private string portrait_ = "";
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public string Portrait {
            get { return portrait_; }
            set {
              portrait_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
          }

          /// <summary>Field number for the "name_show" field.</summary>
          public const int NameShowFieldNumber = 5;
          private string nameShow_ = "";
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public string NameShow {
            get { return nameShow_; }
            set {
              nameShow_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public override bool Equals(object other) {
            return Equals(other as MuteUser);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public bool Equals(MuteUser other) {
            if (ReferenceEquals(other, null)) {
              return false;
            }
            if (ReferenceEquals(other, this)) {
              return true;
            }
            if (UserId != other.UserId) return false;
            if (UserName != other.UserName) return false;
            if (MuteTime != other.MuteTime) return false;
            if (Portrait != other.Portrait) return false;
            if (NameShow != other.NameShow) return false;
            return Equals(_unknownFields, other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public override int GetHashCode() {
            int hash = 1;
            if (UserId != 0L) hash ^= UserId.GetHashCode();
            if (UserName.Length != 0) hash ^= UserName.GetHashCode();
            if (MuteTime != 0) hash ^= MuteTime.GetHashCode();
            if (Portrait.Length != 0) hash ^= Portrait.GetHashCode();
            if (NameShow.Length != 0) hash ^= NameShow.GetHashCode();
            if (_unknownFields != null) {
              hash ^= _unknownFields.GetHashCode();
            }
            return hash;
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public override string ToString() {
            return pb::JsonFormatter.ToDiagnosticString(this);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public void WriteTo(pb::CodedOutputStream output) {
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
          #else
            if (UserId != 0L) {
              output.WriteRawTag(8);
              output.WriteInt64(UserId);
            }
            if (UserName.Length != 0) {
              output.WriteRawTag(18);
              output.WriteString(UserName);
            }
            if (MuteTime != 0) {
              output.WriteRawTag(24);
              output.WriteInt32(MuteTime);
            }
            if (Portrait.Length != 0) {
              output.WriteRawTag(34);
              output.WriteString(Portrait);
            }
            if (NameShow.Length != 0) {
              output.WriteRawTag(42);
              output.WriteString(NameShow);
            }
            if (_unknownFields != null) {
              _unknownFields.WriteTo(output);
            }
          #endif
          }

          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
            if (UserId != 0L) {
              output.WriteRawTag(8);
              output.WriteInt64(UserId);
            }
            if (UserName.Length != 0) {
              output.WriteRawTag(18);
              output.WriteString(UserName);
            }
            if (MuteTime != 0) {
              output.WriteRawTag(24);
              output.WriteInt32(MuteTime);
            }
            if (Portrait.Length != 0) {
              output.WriteRawTag(34);
              output.WriteString(Portrait);
            }
            if (NameShow.Length != 0) {
              output.WriteRawTag(42);
              output.WriteString(NameShow);
            }
            if (_unknownFields != null) {
              _unknownFields.WriteTo(ref output);
            }
          }
          #endif

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public int CalculateSize() {
            int size = 0;
            if (UserId != 0L) {
              size += 1 + pb::CodedOutputStream.ComputeInt64Size(UserId);
            }
            if (UserName.Length != 0) {
              size += 1 + pb::CodedOutputStream.ComputeStringSize(UserName);
            }
            if (MuteTime != 0) {
              size += 1 + pb::CodedOutputStream.ComputeInt32Size(MuteTime);
            }
            if (Portrait.Length != 0) {
              size += 1 + pb::CodedOutputStream.ComputeStringSize(Portrait);
            }
            if (NameShow.Length != 0) {
              size += 1 + pb::CodedOutputStream.ComputeStringSize(NameShow);
            }
            if (_unknownFields != null) {
              size += _unknownFields.CalculateSize();
            }
            return size;
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public void MergeFrom(MuteUser other) {
            if (other == null) {
              return;
            }
            if (other.UserId != 0L) {
              UserId = other.UserId;
            }
            if (other.UserName.Length != 0) {
              UserName = other.UserName;
            }
            if (other.MuteTime != 0) {
              MuteTime = other.MuteTime;
            }
            if (other.Portrait.Length != 0) {
              Portrait = other.Portrait;
            }
            if (other.NameShow.Length != 0) {
              NameShow = other.NameShow;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public void MergeFrom(pb::CodedInputStream input) {
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
          #else
            uint tag;
            while ((tag = input.ReadTag()) != 0) {
            if ((tag & 7) == 4) {
              // Abort on any end group tag.
              return;
            }
            switch(tag) {
                default:
                  _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                  break;
                case 8: {
                  UserId = input.ReadInt64();
                  break;
                }
                case 18: {
                  UserName = input.ReadString();
                  break;
                }
                case 24: {
                  MuteTime = input.ReadInt32();
                  break;
                }
                case 34: {
                  Portrait = input.ReadString();
                  break;
                }
                case 42: {
                  NameShow = input.ReadString();
                  break;
                }
              }
            }
          #endif
          }

          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
            uint tag;
            while ((tag = input.ReadTag()) != 0) {
            if ((tag & 7) == 4) {
              // Abort on any end group tag.
              return;
            }
            switch(tag) {
                default:
                  _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                  break;
                case 8: {
                  UserId = input.ReadInt64();
                  break;
                }
                case 18: {
                  UserName = input.ReadString();
                  break;
                }
                case 24: {
                  MuteTime = input.ReadInt32();
                  break;
                }
                case 34: {
                  Portrait = input.ReadString();
                  break;
                }
                case 42: {
                  NameShow = input.ReadString();
                  break;
                }
              }
            }
          }
          #endif

        }

      }
      #endregion

    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
