<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\AioTieba4DotNet\AioTieba4DotNet.csproj" />
        <ProjectReference Include="..\AioTieba4DotNet.Tests.Platform\AioTieba4DotNet.Tests.Platform.csproj" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Contracts\Baselines\public-api.txt" />
    </ItemGroup>

</Project>
